### ISSUE TITLE
exp/ticker: create an orderbook scraper to compute stats

### ISSUE THREAD

**Issue by accordeiro** [stellar/go#1089]
Create a script that scrapes orderbooks to compute spreads and other stats.

Tasks:
- [x] Adapt db models
- [x] Create scripts
- [x] Write tests
- [x] Adapt the market data aggregator to also include the stats
- [x] Adapt the JSON exporter to also provide the computed stats on markets.json
- [x] Add GraphQL support
- [x] Add cron job to refresh orderbook stats

**Comment by accordeiro** [comment]
Closing this, as the functionality would be identical to what is already provided by the [Horizon Orderbook Details Endpoint](https://www.stellar.org/developers/horizon/reference/endpoints/orderbook-details.html) [CC @tomquisel].

**Comment by tomquisel** [comment]
@accordeiro I think the idea of this scraper is to add orderbook stats to the ticker, so a site can quickly look at the spreads on all markets without making many requests to the Horizon orderbook endpoint.

In the StellarX GraphQL schema, the `OrderBookStats` struct is included for each market:
```graphql
type OrderbookStats {
  nBids: Int!
  bidVolume: String!
  bidMax: String!
  nAsks: Int!
  askVolume: String!
  askMin: String!
  spread: String
  spreadMidPoint: String
}
```

I think you can provide all this information even in `markets.json`, but you'd have to be clever about aggregating across markets since `bidMax` and `askMin` could potentially cross.
