### ISSUE TITLE
txnbuild: remove asset issuer requirement for allow_trust 

### ISSUE THREAD

**Issue by poliha** [stellar/go#1330]
`txnbuild` requires asset issuer for `allow_trust` operations. This is in contrast to other SDKs that require just the asset code. 
This should be changed so that only the asset code is required. Ideally we would want to limit the change to only the allow trust operation because we require asset issuers for other operations such `change_trust`

**Comment by ire-and-curses** [comment]
This happens because `txnbuild` assumes assets must have an issuer, but the underlying XDR does not. It's an odd situation, because for some uses a partially configured asset is sufficient, but for others it is not. 

There are several possible approaches we could take:

1. We could modify `allow_trust` so that an Asset that was passed in without an issuer would be sufficient. At the moment this will fail [here](https://github.com/stellar/go/blob/e5e03dc34e2d428eb4eb202c1d5e0917b51204db/txnbuild/allow_trust.go#L33). One approach is to build an `xdr.AllowTrustOpAsset` directly, using only the code, rather than by converting first to `xdr.Asset`.
2. Another option is to change `txnbuild.Asset.ToXDR()` so that converting to an XDR asset without an issuer is no longer an error (matching the underlying XDR's view). This weakens the checking in `change trust`. To get back to the current behaviour, we would then have to add validation for the presence of the issuer to that operation's construction.
3. A third option is to change the `allow_trust` API to just require a code, since this is actually all that's needed. This would be a breaking API change.

**Comment by poliha** [comment]
Closed in #1439. Went with the first suggestion from above as this guarantees no changes to the current API and its effect is limited to only the `AllowTrust` operation
