### ISSUE TITLE
horizon db clear command does not clear all tables

### ISSUE THREAD

**Issue by brianc-tbcasoft** [stellar/go#1371]
Left out are:

* asset_stats
* history_accounts
* history_assets

was there a reason why these are not included?

**Comment by ire-and-curses** [comment]
Relevant code: https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/ingestion.go#L25

This looks like a bug to me. The individual tables are hardcoded so we could have forgotten to add these others. @bartekn?

**Comment by bartekn** [comment]
I think it's because `start` and `end` params on `Clear`. Basically `Clear` removes data between two given ledgers. `history_accounts`, `history_assets` and `asset_stats` don't have [`toid`](https://godoc.org/github.com/stellar/go/services/horizon/internal/toid) (ID that contains ledger sequence) so they are not removed.

**Comment by brianc-tbcasoft** [comment]
is there a point to re-using the ```Clear``` method with ledger range params (vs something like a truncate) given as is, the ```db clear``` command is meant to clear the db completely?

**Comment by bartekn** [comment]
@brianc-tbcasoft you're right. We need another function that removes all data from a DB.

**Comment by bartekn** [comment]
Closed in #1416.

**Comment by ire-and-curses** [comment]
@brianc-tbcasoft Thanks for raising this issue and the PR you provided, much appreciated!
