### ISSUE TITLE
Intermittent error in TestVerifyChallengeTxSigned on CircleCI

### ISSUE THREAD

**Issue by howardtw** [stellar/go#1589]
I ran into an unexpected error in TestVerifyChallengeTxSigned test during this CircleCI run:
https://circleci.com/gh/stellar/go/5451?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

--- FAIL: TestVerifyChallengeTxSigned (0.02s)
	Error Trace:	transaction_test.go:1329
	Error:		Received unexpected error:
			transaction is not within range of the specified timebounds
			github.com/stellar/go/support/errors.New
				/go/src/github.com/stellar/go/support/errors/main.go:36
			github.com/stellar/go/txnbuild.VerifyChallengeTx
				/go/src/github.com/stellar/go/txnbuild/transaction.go:444
			github.com/stellar/go/txnbuild.TestVerifyChallengeTxSigned
				/go/src/github.com/stellar/go/txnbuild/transaction_test.go:1328
			testing.tRunner
				/usr/local/go/src/testing/testing.go:777
			runtime.goexit
				/usr/local/go/src/runtime/asm_amd64.s:2361
		

	Error Trace:	transaction_test.go:1330
	Error:		Not equal: 
			expected: true
			received: false
	Messages:	challenge should be valid

**Comment by ire-and-curses** [comment]
This is pretty mysterious. I ran

 for i in {1..1000}; do go test -run TestVerifyChallengeTxSigned . -count 1; done

and couldn't repro.

Rechecking the code all looks correct. I'm wondering whether something odd happened on the Circle CI side, like a container pause or something.

Could be a freak accident. Please post if it happens again and we'll add more debugging to try and track this down.

**Comment by howardtw** [comment]
I actually got another related error again in this [run](https://circleci.com/gh/stellar/go/5646?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

```
--- FAIL: TestVerifyChallengeTxNotSigned (0.07s)
	Error Trace:	transaction_test.go:1309
	Error:		"transaction is not within range of the specified timebounds" does not contain "transaction not signed by GAS4V4O2B7DW5T7IQRPEEVCRXMDZESKISR7DVIGKZQYYV3OSQ5SH5LVP" 
```

**Comment by ire-and-curses** [comment]
I think I've found the problem.

`BuildChallengeTx()` has the argument `timebound time.Duration`. This duration has [units of nanoseconds](https://golang.org/pkg/time/#Duration). Our test looks like this:

```golang
func TestVerifyChallengeTxNotSigned(t *testing.T) {
	kp0 := newKeypair0()
	kp1 := newKeypair1()

	// transaction not signed by client
	newChallenge, err := BuildChallengeTx(kp0.Seed(), kp1.Address(), "sdf", network.TestNetworkPassphrase, 300)
	assert.NoError(t, err)
	isValid, err := VerifyChallengeTx(newChallenge, kp0.Address(), network.TestNetworkPassphrase)
	if assert.Error(t, err) {
		assert.Contains(t, err.Error(), "transaction not signed by "+kp1.Address())
	}
	assert.Equal(t, false, isValid, "challenge should not be valid")
}
```
In other words when building the Tx, we are setting timebounds that are within 300ns of each other (not 300s). This is leading to intermittent failures because the whole test must complete within the same Unix epoch second (the verify test) to pass.

We can easily fix the tests (change `300` to `300000000000`), but the bigger issue is that the function should accept `seconds int64`, not `nanoseconds time.Duration`. This is more convenient, more intuitive and also consistent with the Timebounds API in `timebounds.go`. Technically this is a breaking change unfortunately, but since the behaviour is so unintuitive (and the tests are misleading) I think we should just fix it immediately as a patch, before people start using the function in production.

@poliha @howardtw @abuiles what do you think?

**Comment by poliha** [comment]
Thanks for looking into this more. There  are a couple of this we should do
- Fix the tests: We should use `time.Duration` types, e.g `time.Duration(5*time.Minute)`
- Indicate in docstring that the timebound has seconds precision
- Add a check for cases when the supplied timebound is less than `time.Second`
These are the immediate action points. In the future a broader discussion on consistency among types and breaking changes can be done across the repo.

**Comment by howardtw** [comment]
How about we keep the type `time.Duration`, which is `int64` by default, and we add `timebound = timebound * time.Second` in the beginning of the function? Of course we will make it clear in the function comment that this argument is second-based, not nano-second-based. I don't have a strong opinion about how we should fix it. Just a thought.
