### ISSUE TITLE
Horizon reingest has no progress indicator

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#1625]
It would improve usability for Horizon admins to add a progress indicator to the `horizon db reingest` command.

Ideally it would report what ledger it's on, how many it's processed, how many more there are to go, percent complete, and an estimated time to completion

**Comment by bartekn** [comment]
I think it's done. Currently when reingestion is running it prints per ledger status updates. It doesn't print percent complete but right now you always need to pass the range (from/to ledger) you want to reingest so it's easy to calculate. Getting a good ETA will not be possible because ingestion time depends on a number of ops in a ledger and we don't have this information before actually reading the ledger data.

Feel free to reopen if you think we should add more info.
