### ISSUE TITLE
Make sure stale data is not served when rebuilding state

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1663]
When ingest version is upgraded (`expingest.CurrentVersion++`) Horizon will clear all state-related tables and rebuild the state using state pipeline. At this step ledger pipeline is not run waiting for the state ingestion to complete.

It seems possible that during state ingestion a stale data connected to ledger entries can be served (`/accounts`, `/offers`, `/paths`). It seems not dangerous when all endpoints are migrated to the new system but now it can break some use cases (ex. comparing the current balance of an account with transactions since last check).

**Comment by ire-and-curses** [comment]
Maybe the best thing is just to report the endpoint as unavailable until ingestion is caught up.

**Comment by tamirms** [comment]
If the ingest version is upgraded the last ingested ledger in the db is set to 0:

https://github.com/stellar/go/blob/master/services/horizon/internal/expingest/main.go#L232-L244

The [`requiresExperimentalIngestion()`](https://github.com/stellar/go/blob/master/services/horizon/internal/middleware.go#L225-L236) middleware actually checks that the last ingested ledger is greater than 0.

However, this check by itself isn't sufficient because the [code](https://github.com/stellar/go/blob/master/services/horizon/internal/expingest/main.go#L232-L244) which sets the last ingested ledger to 0 is wrapped in a transaction and that transaction is only committed at the end of the state pipeline.

**Comment by bartekn** [comment]
> However, this check by itself isn't sufficient because the code which sets the last ingested ledger to 0 is wrapped in a transaction and that transaction is only committed at the end of the state pipeline.

 Yes, @tamirms is right, this is exactly the case. None of Postgres isolation levels allow reading uncommited changes. Maybe we can add another value to key store, ex. `exp_state_building`. Before state pipeline is started we create a new DB transaction (by cloning DB session), change the `state_building` value to `true` and commit right away. Then in middleware we check `exp_state_building` value instead of `exp_last_ingested_ledger`.

**Comment by bartekn** [comment]
Alternatively, we can compare `exp_last_ingested_ledger` with the last ledger in core. This will solve stale data in state endpoints as well as history endpoints but also prevent serving stale data when ingestion is lagging.

**Comment by bartekn** [comment]
Closed in #1847.
