### ISSUE TITLE
All Assets should trigger on set options

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#182]
premature postgres transaction termination issue, see TODOs in code.

**Comment by ire-and-curses** [comment]
@nikhilsaraf Could you describe the problem a little more? I guess you're talking about [this part](https://github.com/stellar/go/blob/81f17f70e55bc0fad7d196e048d9119e9c57827a/services/horizon/internal/ingest/asset_stat.go#L74) of the code?

**Comment by bartekn** [comment]
@ire-and-curses exactly. In the function you linked we register all assets that were modified in the ledger (so that we know what assets we want to update when calculating asset stats). `set_options` operation can update `home_domain` so also a link to [`stellar.toml`](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md) file that is displayed in asset stats record.

Discussion in this comment: https://github.com/stellar/go/pull/147#discussion_r150935188.

**Comment by bartekn** [comment]
> @ire-and-curses Additionally, certain assets are modified very frequently so we would not want their stats to be updated every ledger. We can update assets every N ledgers by collecting/aggregating the assetsModified in a table and then having a job that updates these assets in batches of size K to spread the load. This way we can spread out the updates over multiple ingestion cycles (batching) and also reduce the total number of updates (aggregation).

Sounds good but let's create another issue for this. This one is only for updating stats when `set_options` operation is sent.

**Comment by nikhilsaraf** [comment]
@bartekn agreed, separate issue is better.

**Comment by bartekn** [comment]
The new ingestion system fixed all issues related to asset stats updates.
