### ISSUE TITLE
services/horizon or services/ticker: create an endpoint that provides the total XLM supply

### ISSUE THREAD

**Issue by accordeiro** [stellar/go#1916]
This endpoint is requested by CoinMarketCap. CMC defines the **total supply** as the total amount of coins in existence right now, minus any coins that have been verifiably burned.

**Comment by accordeiro** [comment]
Note: the endpoint should **only** return the numeric value, similar to [this example](http://chainz.cryptoid.info/grs/api.dws?q=totalcoins).

**Comment by leighmcculloch** [comment]
Got a few questions that I might have already missed conversations about:

1. What's the motivation for a raw text number and not JSON like the other other endpoints on the Ticker API? Is there a common format that we're targeting?

2. If we only want to surface supply information for the native asset and not all assets have we considered adding this endpoint to Horizon?

3. If Ticker, I think this endpoint should be able to get the supply of any asset. We can implement just native to begin with, but it should be in the lead to supporting any asset long term otherwise it feels a little out-of-place in Ticker since Ticker treats the native asset like any other asset and it is focused on the DEX.

4. How should the supply be defined by this endpoint, and would it be worthwhile for the endpoint to return more than one value and to display different definitions of supply transparently? e.g. It could include a values for:
   - The total supply on the network.
   - Total supply not including burned amounts in locked accounts (i.e. burned assets).
   - Total supply not including burned amounts, not including amounts not distributed by SDF yet.
   - ?

**Comment by accordeiro** [comment]
Those are great questions! :)

> 1. What's the motivation for a raw text number and not JSON like the other other endpoints on the Ticker API? Is there a common format that we're targeting?

Yep! This was specifically requested by CMC. That said, if we want to use JSON I'm sure they'd be flexible to accommodate.

> 2. If we only want to surface supply information for the native asset and not all assets have we considered adding this endpoint to Horizon?

That's a great point – @ire-and-curses do you think Horizon would be a better home for this simple endpoint? Maybe it's already possible to retrieve that info from the Horizon API?

> 3. If Ticker, I think this endpoint should be able to get the supply of any asset. We can implement just native to begin with, but it should be in the lead to supporting any asset long term otherwise it feels a little out-of-place in Ticker since Ticker treats the native asset like any other asset and it is focused on the DEX.

Agreed! I love the idea of starting with the native but ensuring we'll add support for other assets. We just need to make sure we have a good way to get the supplies from Horizon. I know we can get that info from the TOML files (and we already store that in the Ticker DB), but I'm not sure we'd want to rely on the TOML info (vs the actual supplies on ledger).

> 4. How should the supply be defined by this endpoint, and would it be worthwhile for the endpoint to return more than one value and to display different definitions of supply transparently? e.g. It could include a values for:

This is information is definitely valuable, but I'm not sure we need to focus on providing those for the purpose of this issue specifically, since this involves more complex logic (mapping out locked accounts, SDF accounts, etc).

Do these answers make sense? @tomquisel @rice2000 please feel free to add any extra context / inputs here :)

**Comment by ire-and-curses** [comment]
> That's a great point – @ire-and-curses do you think Horizon would be a better home for this simple endpoint? Maybe it's already possible to retrieve that info from the Horizon API?

AFAIK it's not possible to get this from Horizon at present. The total number is available in stellar-core's data structures as `LedgerHeader.totalCoins` (expressed in stroops) so in theory it could be accessed from the ingested ledger header. I don't know that I see a ton of value in exposing this in Horizon though as a whole new endpoint. To account for the burned lumens would need hardcoding which would make Horizon less general for e.g. private networks.

**Comment by leighmcculloch** [comment]
@ire-and-curses Do you think it'd be feasible as part of ingestion to store details about lumen supply, e.g. total lumen supply, lumen supply burned (held by locked accounts), etc?

**Comment by tomquisel** [comment]
The assets endpoint in Horizon already exposes total supply: https://www.stellar.org/laboratory/#explorer?resource=assets&endpoint=single&network=public

maybe no need to reinvent the wheel there?

**Comment by leighmcculloch** [comment]
The immediate goal of this issue is going to be satisfied by stellar/dashboard#128.

I think we can shift this issue to focus on what supply market data do we need to surface in light that assets, including the native asset, can be burned by locking them up in accounts that have no signers. Is it valuable for us to surface that supply data from Horizon or Ticker? Or no?

**Comment by tomquisel** [comment]
Oh, I love the idea of exposing supply for assets excluding burned assets and assets in the distribution account(s). I'm not sure how easy it is to detect those, but it would certainly be valuable. Maybe it should even be in Horizon at that point since "circulating supply" is a pretty foundational number to have.

**Comment by bartekn** [comment]
> Is it valuable for to surface metrics either via Horizon or Ticker about not just how much supply an asset has, but how much of that supply is burned or not?

I think as a part of the future Stellar Protocol upgrade we should remove `GALAXYVOID...` account from the ledger and update the numbers in core. It will be extremely confusing otherwise.

**Comment by leighmcculloch** [comment]
@bartekn I don't think that solves the need for insight holistically because anyone can lockup any asset in an account with no signers.

If we were to make that change holistically, by having core delete accounts that are locked at the end of a transaction it'd be a big change since assets can actually disappear outside of the issuers control. That'd help clean up accounts that won't serve anyone again.

Regardless I think the transparency and metrics are still worthwhile.

**Comment by ire-and-curses** [comment]
My opinion: Horizon's purpose is to reflect the underlying blockchain. Total XLM supply is tracked in stellar-core, so Horizon could reasonably present that.

But other things like burned coins, SDF-held coins etc are a construct of SDF, and aren't represented in the ledger. I think that makes it problematic to present them in Horizon. For example, if this was a private network, how would this work? The Horizon implementation would have to know about specific accounts. This feels like the wrong layer.

A higher-level service like the dashboard seems like a better place to encode this distribution-specific information.

**Comment by leighmcculloch** [comment]
>But other things like burned coins, SDF-held coins etc are a construct of SDF, and aren't formally represented in the ledger. I think that makes it problematic to present them in Horizon.

I agree with the SDF-held assets being more appropriately communicated in stellar/dashboard#128. I don't think we need to surface them from Horizon.

But anyone can burn the native asset, or a non-native asset, that's on the ledger. My earlier question was, is the burned quantity of an asset (native or not) a useful metric to expose from Horizon? I think so.

**Comment by ire-and-curses** [comment]
> But anyone can burn the native asset, or a non-native asset, that's on the ledger. My earlier question was, is the burned quantity of an asset (native or not) a useful metric to expose from Horizon? I think so.

Yeah but what does it mean to burn? The XLM doesn't disappear. It just goes to an account that happens to be inaccessible. I don't know how Horizon is supposed to know this, or keep it up to date.

**Comment by leighmcculloch** [comment]
Core knows this, it's in the `accounts` table. Any account with the value of the first byte of the `thresholds` column and any keys in the `signers` column set to a weight that is below the low/med/high thresholds in the 1st, 2nd, and 3rd bytes of the `thresholds` column. Definitely not something that is easy to query, but the data is there, it'd need to be ingested into an easier to query structure.

**Comment by tomquisel** [comment]
Agreed, I think it's a reasonable feature to expose circulating supply for assets in Horizon. The definition would be what @leighmcculloch is suggesting, where balances in provably inaccessible accounts are excluded. My earlier suggestion of excluding distribution accounts isn't appropriate for Horizon as a few of you have pointed out since there's no on-chain way to determine what a distribution account is.

**Comment by ire-and-curses** [comment]
I think this would be very challenging to implement. After initial ingestion and mapping to some custom data structure, there is an ongoing burden for Horizon to listen to all existing inaccessible accounts for balance changes, and also track signature+weighting changes to **all accounts**, since an account could become permanently inaccessible at any time (and would then need to be added to the list). For reference, currently there are over 4M accounts on the network.

**Comment by ire-and-curses** [comment]
Hmm I just realised that `total_coins` is actually exposed in `/ledgers`. The number obviously depends on which ledger you asked for, but you can get latest ledger easily:

- Genesis: https://horizon.stellar.org/ledgers/ - total_coins: "100000000000.0000000"
- Latest: https://horizon.stellar.org/ledgers/?order=desc&limit=1  - total_coins:  "105443902087.3472865"
