### ISSUE TITLE
services/horizon/expingest: False positive from StateVerifier

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2038]
### What version are you using?

Horizon 0.23.1, 0.24.0 RC

### What did you do?

After processing pubnet checkpoint ledger [27207615](https://horizon.stellar.org/ledgers/27207615) state verification failed after a couple seconds with the following error:
```
addAccountsToStateVerifier failed: Entry does not match the fetched entry. Expected: AZ8nvwAAAAAAAAAADq+QhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcJOKW6QDjhboAAH7VAAAAAAAAAAEAAAAAnaQ/bEto5UuPoNHBfWYzIDSa5tidi+7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA== (pretransform = AZ8nvwAAAAAAAAAADq+QhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcJOKW6QDjhboAAH7VAAAAAAAAAAEAAAAAnaQ/bEto5UuPoNHBfWYzIDSa5tidi+7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==), actual: AZ8nvwAAAAAAAAAADq+QhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcEWT3KQDjhboAAH7VAAAAAAAAAAEAAAAAnaQ/bEto5UuPoNHBfWYzIDSa5tidi+7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
```
XDR view: [expected](https://www.stellar.org/laboratory/#xdr-viewer?input=AZ8nvwAAAAAAAAAADq%2BQhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcJOKW6QDjhboAAH7VAAAAAAAAAAEAAAAAnaQ%2FbEto5UuPoNHBfWYzIDSa5tidi%2B7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%3D%3D&type=LedgerEntry&network=public), [actual](https://www.stellar.org/laboratory/#xdr-viewer?input=AZ8nvwAAAAAAAAAADq%2BQhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcEWT3KQDjhboAAH7VAAAAAAAAAAEAAAAAnaQ%2FbEto5UuPoNHBfWYzIDSa5tidi%2B7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%3D%3D&type=LedgerEntry&network=public).

This occurred in multiple Horizon servers after processing the ledger above.

The difference seems to be due to transaction [`ea1e9...30f6a`](https://horizon.stellar.org/transactions/ea1e96dd4aa8a16e357842b0fcdb66c1ab03fade7dcd3a99f88ed28ea8c30f6a). The difference in account balance is 32.7 XLM. After checking the database state manually the balance of the account above was correct. After marking the state as valid manually (`exp_state_invalid=false` in `key_value_store`) the consecutive state verifications did not find any differences between DB state and state in history archive.

**Comment by tamirms** [comment]
I don't think it's a false positive. I was able to reproduce this error consistently.

In ledger 27207615, there were two transactions which affected the balance of account GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A.

the first transaction was https://horizon.stellar.org/transactions/ea1e96dd4aa8a16e357842b0fcdb66c1ab03fade7dcd3a99f88ed28ea8c30f6a

this transaction was applied correctly to the database.

the second transaction in ledger 27207615 which affected GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A was:

https://horizon.stellar.org/transactions/b7ce88831f0e79aa0cfe3665cd360ca41ce5e24c77e254852184a143589ee29c

the LedgerEntry included in this transaction can be viewed here:

https://www.stellar.org/laboratory/#xdr-viewer?input=AZ8nvwAAAAAAAAAADq%2BQhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAEcEWT3KQDjhboAAH7VAAAAAAAAAAEAAAAAnaQ%2FbEto5UuPoNHBfWYzIDSa5tidi%2B7SDw52gOrFe4UAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA%3D&type=LedgerEntry&network=public

the balance applied to the account matches the value which appeared in the state verification error.  

Interestingly, transaction b7ce88831f0e79aa0cfe3665cd360ca41ce5e24c77e254852184a143589ee29c is actually a failed transaction. 

We used to ignore failed transactions in the database ledger processor but we removed that check in this PR:

https://github.com/stellar/go/pull/1906/files#diff-df00ac69b2afa913cd5937949c83c929L127

I think we need clarification on how ingestion should handle failed transactions because it seems like, if we did not update the database with the change from this failed transaction then, our database would have been consistent with the history archive snapshot and we wouldn't have triggered the state verification error.

**Comment by bartekn** [comment]
@tamirms great catch! I found a data race in the pipeline (https://github.com/stellar/go/issues/2046) and I was about to confirm if it's really a root cause today but it seems you are right.

It looks the root cause is that we are processing fee meta, then tx meta for each transaction but we should process ALL fee metas (of all txs) first and then ALL tx metas (of all txs). In other words we process:
```
TX1_FEE_META, TX1_TX_META, TX2_FEE_META, TX2_TX_META, ...
```
but we should:
```
TX1_FEE_META, TX2_FEE_META, TX1_TX_META, TX2_TX_META, ...
```
It's incredible that we haven't seen this before but at the same time it's great that `StateVerifier` helped again and that we still serve `/accounts/{id}` data from stellar-core db.

I'm going to prepare a fix soon.

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/go/pull/2050.
