### ISSUE TITLE
Create cron kubernetes job that runs `horizon-cmp history`

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2249]
Create a cron (every 5/10 minutes) kubernetes job that runs #2227:
```
horizon-cmp -b [history.stellar.org] -t [horizon-stg-pubnet] history
```
By default it checks last 120 ledgers (around 10 mins) so ranges should overlap to not miss any ledges. If non-zero exit code is returned it should send a Slack notification.

**Comment by abuiles** [comment]
@bartekn  I was discussing this with @tamirms and he suggested a different approach -- instead of doing this as a cron job, we could create a service that runs horizon-cmp and then exposes the results as prometheus metrics.

I think that approach is more robust since it might also leave us with some shared infra that we can use for other tasks of this kind and we can built on top of the alerting infrastructure which prometheus has already. 

Bartek - what do you think about it?

**Comment by abuiles** [comment]
@bartekn maybe it would be worth taking a step back and figuring what's the problem we want to solve and how each tool fits into this problem. 

@tamirms also has some ideas around this, maybe we can start a document for brainstorming and then we can start talking about how to solve the problem. cc @ire-and-curses

**Comment by ire-and-curses** [comment]
Yeah I agree with this approach. A document with what we're trying to achieve that we can discuss would be ideal. I can see several possible goals and they may need different approaches. For example, some goals might be:

* moving us in the direction of continuous deployment
* reducing our manual testing burden by auto-running some tests
* seeking out regressions
* giving us better alerting at a level more fine than "Horizon is down"

These may need multiple solutions, and some are more important than others.
