### ISSUE TITLE
Feature Request: Allow filtering accounts by asset and is_authorized.

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2254]
### What problem does your feature solve?
Right now you can filter all accounts who have a trust line to an asset using the `?asset` query parameter in `/accounts`. This end points return both accounts who are authorized and accounts which are not authorized. 

### What would you like to see?
We should have an extra query parameter to show  only `authorized` or `unauthorized`. 

I think we could have a query param called `is_asset_authorized` which takes `1` for true or `0` for false.

The following request will return all the accounts with a trust line to the given asset pending authorization.

`accounts?asset=COP:GAEDLNMCQZOSLY7Y4NW3DTEWQEVVCXYYMBDNGPPGBMQH4GFYECBI7YVK&is_asset_authorized=0`

### What alternatives are there?

Right now you can find all the authorized or unauthorized accounts by loading all the pages and filtering by `is_authorized.

**Comment by ire-and-curses** [comment]
I like this idea. I think it's more standard to have boolean query params as `true|false` rather than numbers though.

* [Github API example](https://developer.github.com/v3/activity/watching/#parameters)
* [Sane restful API design guidelines](https://coderwall.com/p/gbxelq/simple-rules-for-a-sane-restful-api-design)
* [StackOverflow question](https://stackoverflow.com/questions/39979533/how-should-rest-api-accept-boolean-values)

**Comment by OwenJacob** [comment]
Could the consistency issue here: https://github.com/stellar/go/issues/2200 be addressed as well please!

**Comment by bartekn** [comment]
This requires an extra index and there isn't much interest in this feature. Closing for now.
