### ISSUE TITLE
Odd 400 / 500 issues when attempting to refund funded accounts.

### ISSUE THREAD

**Issue by tyvdh** [stellar/go#2271]
### What version are you using?
`"stellar-sdk": "^4.0.0"`

### What did you do?
Attempting to refund a funded account. Goofy I know but it surfaced some odd inconsistent error handling which should likely be addressed.

Screencast of the issue: http://tyler.link/QsvRGA

You can reproduce the issue yourself here:
https://hack-stellar.now.sh/

Just click "Generate Keypair" and then keep clicking "Fund Account"

### What did you expect to see?
Consistent 400 error
```json
{
  "type": "https://stellar.org/horizon-errors/bad_request",
  "title": "Bad Request",
  "status": 400,
  "detail": "createAccountAlreadyExist (AAAAAAAAAGT/////AAAAAQAAAAAAAAAA/////AAAAAA=)"
}
```

### What did you see instead?
Occasional inconsistent 500 error
```json
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue."
}
```

**Comment by bartekn** [comment]
I think the bug is here:
https://github.com/stellar/go/blob/f95820107d5f9fca521874e25d640354c3d3aa18/services/friendbot/internal/minion.go#L35-L55

The code doesn't `return` after sending to channel but the other go routine `close` the channel after reading the first message:
https://github.com/stellar/go/blob/f95820107d5f9fca521874e25d640354c3d3aa18/services/friendbot/internal/friendbot.go#L33-L34

So another attempt to write to a channel will panic with `send on closed channel` error.
