### ISSUE TITLE
Test support for CAP 28 (clear pre-auth transaction signer on failed transactions)

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#2377]
Protocol 13 will implement [CAP 28](clear pre-auth transaction signer on failed transactions). This is a stellar-core internal change that shouldn't affect downstream. However there's the possibility that Horizon's effects could change. Find out by ingesting new ledgers from stellar-core.

**Comment by 2opremio** [comment]
I have tested pre-auth transactions on a local, standalone network. I have observed the following:

1. Effects don't change. There is no  "signer_removed" effect associated with a pre-auth signer being implicitly cleared due to its corresponding transaction being submitted; regardless of whether the transaction submission fails or not.
2. Horizon doesn't  remove the pre-auth signer is not removed from the account if the transaction submission fails. This would be fine ... except there is no way to remove the pre-auth signer anymore and it dangles forever. Trying to delete the signer by setting a weight of 0 doesn't help, since core has already removed it.

I will create an issue to fix this.

**Comment by 2opremio** [comment]
As a side note, I think (1) should also be "improved". I think it's unintuitive that a signer is removed magically, without an associated effect. However, this is not a regression.

**Comment by 2opremio** [comment]
> Horizon doesn't remove the pre-auth signer is not removed from the account if the transaction submission fails. This would be fine ... except there is no way to remove the pre-auth signer anymore and it dangles forever. Trying to delete the signer by setting a weight of 0 doesn't help, since core has already removed it.

My local environment seems to be flawed. It turns out Core is not clearing the pre-auth signature. I need to investigate why.

**Comment by 2opremio** [comment]
Well, it turns out that the implementation CAP28 is a lot more subtle than I thought.

In order to get its effect, you need to get transactions in the *same* ledger which individually make sense but which in certain order make the last transaction to be invalid. Thanks a lot to @jonjove for running me through it.

**Comment by 2opremio** [comment]
I managed to reproduce it and the behavior of horizon remains as it was (you **can** remove the signer).
