### ISSUE TITLE
Update Horizon admin guide with nginx setup instructions

### ISSUE THREAD

**Issue by bartekn** [stellar/go#242]
Nginx has to be configured correctly for event source streams: https://serverfault.com/a/801629

**Comment by khelle** [comment]
What exactly needs to be configured? I tried doing proxy via Nginx but without success, this is my nginx config file I tried according to the link @bartekn posted.

```
server {
  listen 14040 ssl default_server;
  server_name _;
  ssl_certificate /etc/nginx/ssl/nginx.crt;
  ssl_certificate_key /etc/nginx/ssl/nginx.key;
  underscores_in_headers on;

  location / {
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/.htpasswd;
    proxy_http_version 1.1;
    proxy_read_timeout 300;
    proxy_set_header  Host $host;
    proxy_set_header  Connection "";
    proxy_set_header  Cache-Control no-cache;
    proxy_set_header  Transfer-Encoding chunked;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-Proto https;
    proxy_set_header  X-Forwarded-For $remote_addr;
    proxy_set_header  X-Forwarded-Host $remote_addr;
    proxy_set_header  X-Accel-Buffering no;
    proxy_pass        https://localhost:15040;
    proxy_pass_request_headers on;
  }
}
```

I am getting ECONNREFUSED regardless If I set Connection, Cache-Control or X-Accel-Buffering. The only option that seems to matter is Transfer-Encoding - if I set it to chunked I get TIMEOUT instead of CONN REFUSED. When I try to access horizon directly (using port 15040 instead of proxy's 14040) everything works fine.

**Comment by bartekn** [comment]
Please use our [StackExchange](https://stellar.stackexchange.com/) for questions.

**Comment by howardtw** [comment]
What's the status of this issue @bartekn ?

**Comment by bartekn** [comment]
@howardtw not done. We need to explain [this](https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate/801629#801629) in Horizon admin guide.

**Comment by ChrisRut** [comment]
I had to add `proxy_buffering off;` in order for it to play nice.
