### ISSUE TITLE
Fast txmeta: clean up single-threaded prototype

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#2551]
Clean up the [single threaded proof-of-concept implementation](https://github.com/stellar/go/pull/2322).

- [x] make sure it builds, clean up rough edges, confirm works as intended for happy path
- [x] fix and add more tests https://github.com/stellar/go/issues/2585
- [x] add `PrepareRange(from, to)` method to `LedgerBackend` interface (see comment)
- [x] Add config values for experimental captive ingestion, add stellar-core path instead of using PATH https://github.com/stellar/go/issues/2584
- [x] start and maintain a list of TODOs to come back to after MVP
- [ ] implement crash/restart logic on the ingestion side of the prototype (@bartekn: is it essential for offline mode demo?)
- [ ] add basic docs (e.g. a README explaining how to play with it)
- [ ] document Horizon / fast stellar-core interface
- [ ] measure ledger ingestion performance so we have a baseline to compare against

Meta issue: #2550

**Comment by bartekn** [comment]
I think adding `PrepareRange(from, to)` method to `LedgerBackend` interface can be a good idea (added to the list above). Currently, a) the catchup to the first ledger in the range happens when `GetLedger` is called and this takes some time, affecting the first ledger processing time (`duration`), b) it ingests up to 17280 per process, so after 17280 ledgers the stellar-core process will be restarted which can affect speed. In `db reingest range` command we know exactly what range Horizon will be processing so we can prepare captive backend to get this specific range and to speed the process.

For ledger backends that don't allow preparing (like DB backend) `PrepareRange` can be a noop or check if the first and the last ledger in the range is present in the backend.

**Comment by bartekn** [comment]
Copying @tamirms's comments here (wanted to merge this PR into a feature branch quickly):
* https://github.com/stellar/go/pull/2322#discussion_r428006453
* https://github.com/stellar/go/pull/2322#discussion_r428009969
* https://github.com/stellar/go/pull/2322#pullrequestreview-415349985

**Comment by bartekn** [comment]
Looks like all the subitems here are done except https://github.com/stellar/go/issues/2815 which is a separate issue now.
