### ISSUE TITLE
Use Horizon DB to implement SequenceProvider

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2577]
The txsub package defines a interface for fetching sequence numbers for a given list of source accounts:

```golang
// SequenceProvider represents an abstract store that can lookup the current
// sequence number of an account.
type SequenceProvider interface {
	// Look up a sequence by address
	Get(addresses []string) (map[string]uint64, error)
}
```

Currently, the only implementation of `SequenceProvider` lives in github.com/stellar/go/services/horizon/internal/db2/core. 

Instead of querying the accounts table from the stellar core db we should be querying the Horizon db to implement the `SequenceProvider` interface.

**Comment by bartekn** [comment]
The only issue we can experience is when Horizon is catching up (seqnums of some accounts may not be up to date). But since https://github.com/stellar/go/commit/63621c7d72ccb451b2762868e4d143f2c2d7176f we require Horizon to be up to date anyway to be able to return a success response so this issue looks good.
