### ISSUE TITLE
Confirm crash/restart works reliably during online mode

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2611]
While we don't care much about crashes in the offline mode (because Horizon is ingesting old ledgers and the process can be simply restarted after a failure) we do in the online mode.

We should check what happens when stellar-core process potentially crashes:
* How long does it take to be able to start streaming ledgers again?
* Does it affect distributed ingestion? A shared lock should be probably released when crash happens when streaming ledger data.
* Ensure the data is not corrupted after a crash.

To check this we can simply kill a stellar-core process during different stages of ingestion.

**Comment by bartekn** [comment]
Most of the items here has been fixed in https://github.com/stellar/go/pull/2803 but I'm not sure Stellar-Core process is properly closed when shutdown is initiated by Horizon. Moving to 1.7.0 milestone.

**Comment by 2opremio** [comment]
@tamirms are you still working on this? I will also assign myself since I already did some testing.

**Comment by tamirms** [comment]
@2opremio sounds good, I haven’t started on this yet

**Comment by 2opremio** [comment]
While running  `stellar/horizon:2cfb2670c` connected to testnet on local kubernetes Cluster, I killed the Captive Core repeatedly.

When killed with `SIGKILL` Captive Core left zombie processes, which Horizon (working as init) didn't reap (see #3217 ) however Horizon always recovered.

On average, I estimate Horizon took around ~60 seconds to re-start ingestion (since captive core starts streaming from the prior checkpoint).

I didn't test distributed ingestion though. @bartekn  should probably create a k8s configuration for this. Let's have a chat on how to do it and I will take care of it.

**Comment by 2opremio** [comment]
I have tested multiple concurrent ingestors and they seem to work fine when one of them is killed.

I have also tested killing the core process while managing in with the captive core remote http server. I have created #3228 with the issues I found.
