### ISSUE TITLE
bifrost: p2sh support?

### ISSUE THREAD

**Issue by ramontayag** [stellar/go#263]
Any plans to support p2sh? Thinking of having deposits go directly to a multi-sig cold storage wallet, controlled by something like Electrum. I'm far less familiar with the options for Ethereum -- like if a smart contract can have a HD wallet of some kind.

**Comment by bartekn** [comment]
I think this would make the process less user-friendly:
* For Bitcoin there is no easy way to add additional data to the transaction. That's why all exchanges generate a separate addresses for user deposits. It will be impossible (or maybe possible with non-standard transaction script but most users wouldn't be able to construct such transaction) to distinguish payments coming to a single address from 2 different users.
* For Ethereum it's easier because you can add data to your transaction however it's more complicated that just sending a payment to a given address.

To solve this you can create a background process that forwards payments from hd-wallet addresses to a multi-sig wallet. Because it's likely that you don't need to move these funds right away you can set a lower fee on these transactions so that they will be added to a block eventually (ex. after 2-3 days). However this worker should work on an offline machine because it will need to have master private key to sign transactions.

Will reopen this when there is interest in this feature from more users.

**Comment by ramontayag** [comment]
@bartekn ok thanks for the response. I want to clarify that it shouldn't make it more complicated to the person depositing. They will just see their own address, like `3Qxxxxxxxxxxx`. Since posting this I did a but more research, and what I'm referring to is hierarchical deterministic multisig (or HDM). I can't tell if there's a standard way to create these.

In case the community shows interest, here are some libraries that do this:
- https://github.com/yariv/HDMNode/blob/master/lib/btcutil.js#L61
- https://github.com/spesmilo/electrum/blob/master/lib/wallet.py#L1770

**Comment by bartekn** [comment]
OK, then I misunderstood you. I thought that you want users to send to a single address but you want to create many P2SH addresses and each user will have it's own.

There's probably a smart way to do it in Bitcoin. However, in Ethereum you'd have to deploy (init) each of the multisig contract before receiving a payment - this requires more coordination and can be expensive (in terms of network fees).
