### ISSUE TITLE
add minimum operation fee to ledger resource

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#293]
In case the network is busy, clients may choose to increase their transaction fee to guarantee submission. To make an educated decision, clients should know what was the minimal fee per operation that made it on the previous ledger/s. Right now, the only way to do so is to query for all ledger transactions.

I propose adding `min_op_fee` to the ledger resources available through `/ledgers`. This will be computed as part of the ingestion process.

**Comment by nullstyle** [comment]
While I think this tactic for helping people submit transactions under network load is viable, I hesitate to decide on this solution:  I think we should first look at the problem of communicating network "weather" to integrators at a holistic level before we decide how we solve the specific problem of addressing fee flux.  

For example, I think we should investigate exposing an independent resource that provides advice for interacting with the network.  I chose "weather" in the previous paragraph because I think the data I have in mind doesn't quite map to the usual operational concepts like telemetry or health checks.  IMO network weather would be an amalgam recorded telemetry (a rolling average of ledger close times would be an example), health checks (stellar-core sync state is an example) and advice (`min_op_fee` would be an example).  Anyways, we can have that brainstorm more easily in person I think.

---

Can you think of other use cases that would justify the added storage cost used by adding a column to `history_ledgers`?  If the only use case we can think of is to help advise a transaction crafter about what fee to use, I would also propose we consider solving the problem directly by adding a `/advise/operation_fee` endpoint or something of that ilk.

**Comment by bartekn** [comment]
Another solution to think about is changing `fee` to `maxFee` on transaction. Then transactions will be sorted by `maxFee` but the lowest value of top of `tx_per_ledger` (currently: 50) will be taken as a fee.

I think partners wouldn't mind to set `maxFee` to even 0.01 USD because the cost is still super low but attackers won't be able to send as many txs as before.

**Comment by tomerweller** [comment]
@bartekn I completely agree. That's a suggestion worthy of the the stellar-core repo. I think @MonsieurNicolas agrees with you. 

@nullstyle yeah a separate resource should suffice, in light of the way I framed the requirement. The only reason I can think of saving this data is to allow for a historical, statistical view, which might be out of the scope of horizon.

**Comment by tomerweller** [comment]
Closing in favor of #516
