### ISSUE TITLE
Add integration tests for Protocol 14

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2939]
Using the new integration tests infrastructure, we should add tests for

- GET `/claimable_balances`.
- GET `/claimable_balances/id`.
- GET `/claimable_balances` filtering by `sponsor`, `claimant`, and `asset`.

See #2916

**Comment by bartekn** [comment]
Here are proposed scenarios for CAP-23, CAP-33 and a mix of CAP-23 and CAP-33:

CAP-23:

1. Submit `create_claimable_balance` with different predicates:
    1. Two successful: native and non-native asset.
    1. One with a predicate that will fail later when calling `claim_claimable_balance`.
1. Check `/claimable_balances` (filter by claimant, asset).
1. Check `/claimable_balances/{id}`.
1. Submit `claim_claimable_balance` for all entries (use claimable balance id returned by Horizon).
1. Check `/operations` if correctly ingested (also check `/operation?include_failed=true` to check failed ops due to invalid predicate).
1. Check `/effects` if correctly ingested.
1. State Verifier [1]

CAP-33:

1. Submit operations to create sponsored ledger entries (account, offer, signer, data, trustline).
1. Check `/accounts` (check signers, trustlines, data), `/offers`.
1. Update sponsorship entry.
1. Check updated sponsor in `/accounts` (check signers, trustlines, data), `/offers`.
1. Check `/operations` if correctly ingested.
1. Check `/effects` if correctly ingested.
1. State Verifier  [1]

Mix CAP-23 & CAP-33:

1. Create sponsored claimable_balance.
1. Check sponsor in `/claimable_balances`.
1. Check `/operations` if correctly ingested.
1. Check `/effects` if correctly ingested.

[1] For State Verification we should probably just check if it completed. You can either use `/metrics` or parse Horizon log.

@Shaptic we can discuss this after team meeting today.

**Comment by tamirms** [comment]
We should add a CAP 33 test which covers the case where a sponsorship can be removed during one-time signer removal.

To trigger a one-time signer removal you need to prepare an account with a pre-auth signer (let’s say for the transaction with hash H) that is sponsored. 

Once transaction H is prepared, submit it.

Afterwards, the pre-auth signer with corresponding sponsorship should be removed.

Note, H can succeed or fail and the signer will be removed in either case.

**Comment by Shaptic** [comment]
Tests for scenarios 1-4 under the CAP23 section above are implemented in the #2991 (draft) PR.

**Comment by bartekn** [comment]
I can add State Verifier test.

**Comment by 2opremio** [comment]
> We should add a CAP 33 test which covers the case where a sponsorship can be removed during one-time signer removal.

This was done at #3050

**Comment by bartekn** [comment]
@stellar/horizon-committers looks like we can close this? 🎉

**Comment by ire-and-curses** [comment]
Yeah I agree - if there are further tests needed, let's add them as separate issues.
