### ISSUE TITLE
Add retries when creating a state reader in the dump ledger script

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2975]
There is a rare race condition where the latest history archive snapshot is not fully published in S3 / cloudflare. In that case, we are able to obtain the latest sequence number but the requests to obtain the bucket list may fail. When that happens the dump ledger script fails here

https://github.com/stellar/go/blob/master/exp/tools/dump-ledger-state/main.go#L233-L235

with an error which looks like:

```
unable to get checkpoint HAS at ledger sequence 31389055: Bad HTTP response '404 Not Found' for GET 'https://history.stellar.org/prd/core-live/core_live_001/history/01/de/f5/history-01def57f.json'
```

To make the dump ledger script more reliable we can we can retry `MakeSingleLedgerStateReader()` with a time delay if it fails with a 404 error.

**Comment by bartekn** [comment]
According to https://github.com/stellar/stellar-core/blob/master/docs/history.md this shouldn't happen:
> The root HAS file is also the last file written to the history archive when any update is made, so represents an atomic "commit point" to changes to the archive.

I started checking [S3 consistency model](https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html) and found this:
> Amazon S3 provides read-after-write consistency for PUTS of new objects in your S3 bucket in all Regions with one caveat. The caveat is that if you make a HEAD or GET request to a key name before the object is created, then create the object shortly after that, a subsequent GET might not return the object due to eventual consistency.

So I think the issue we experienced should not happen until someone made HEAD/GET request to https://history.stellar.org/prd/core-live/core_live_001/history/01/de/f5/history-01def57f.json before it was created.

Sharing just in case someone is wondering how it happened in the future because it confused me too.

**Comment by bartekn** [comment]
Woohoo, S3 is now [strongly consistent](https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/)!

**Comment by 2opremio** [comment]
@tamirms could you check whether the strong consistency of S3 resolves the problem?

**Comment by tamirms** [comment]
I will close the issue and reopen if the error occurs again
