### ISSUE TITLE
It is not documented that Mysql and Postgres are needed to run tests

### ISSUE THREAD

**Issue by mvaneijk** [stellar/go#30]
Currently, running tests locally will fail without these services installed and running.

**Comment by ire-and-curses** [comment]
I absolutely agree that Postgres is required. As I understand it `mysql` tests are skipped if `mysql` is not installed. Is that the case for you @mvaneijk?

**Comment by ire-and-curses** [comment]
It is now documented that Postgres is needed to run tests: https://github.com/stellar/go/blob/master/services/horizon/internal/docs/developing.md.

I'm closing this because `mysql` is an optional requirement, and those tests are skipped if it's not installed. Feel free to reopen if you think more is needed @mvaneijk .
