### ISSUE TITLE
Push stellar/horizon image with stellar-core 14.1.1

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3131]
In https://github.com/stellar/go/pull/3130 I upgraded stellar-core to 14.1.1. in stellar/horizon image but it's pushed on releases only. To be able to use the image in captive core mode in kubernetes we need to push update image to docker repository. Additionally, we can include https://github.com/stellar/go/pull/3104 because it's been fixed in Horizon.

**Comment by tamirms** [comment]
I updated the `stellar/horizon:latest` and `stellar/horizon:1.10.0` docker images so that they include the 14.1.1 version of the stellar core binary.

https://hub.docker.com/layers/stellar/horizon/1.10.0/images/sha256-71e7965f5c8a17e72a14bd660618770f10f374856a5275d52404695c4b720510?context=explore

https://hub.docker.com/layers/stellar/horizon/latest/images/sha256-71e7965f5c8a17e72a14bd660618770f10f374856a5275d52404695c4b720510?context=explore
