### ISSUE TITLE
Research generating stellar-core.cfg in Captive-Core online mode

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3211]
It may be possible to generate Stellar-Core config as we [do in the offline mode](https://github.com/stellar/go/blob/507901ae6f7069a17f23f9c18d557a918d5e5732/ingest/ledgerbackend/stellar_core_runner.go#L90) since we Captive Core mode runs in memory. We need to ensure if there aren't any other config values users may want to change. At the same time we should require providing quorum slices for the config (may use the same toml format, quorum info will be appended to generated config).

**Comment by tamirms** [comment]
In addition to quorum slices we should also allow configuring the http port for captive core

**Comment by 2opremio** [comment]
And in addition, the user may want to tweak the database backend.

On top of that, for things like testing we want to tweak the core configuration (e.g. `MANUAL_CLOSE`).

**Comment by tamirms** [comment]
> And in addition, the user may want to tweak the database backend.

I thought for our use case there is no database backend. captive core will always stream ledgers in memory because we are passing the `--in-memory` flag to the stellar core binary.

**Comment by 2opremio** [comment]
My initial design for this is:

* Replace `--stellar-core-config-path` by `--stellar-captive-core-quorum-path` which would point to a file with `[QUORUM_SET]` entries
* Add `--stellar-captive-core-http-port` which:
  * Defaults to `11626` 
  * Disables the http port if set to `0` (just like it works in the core config file)
* If `--stellar-core-url` is not explicitly set, but `--enable-captive-core-ingestion` is set and `--remote-captive-core-url` isn't set, make `--stellar-core-url` point to `localhost:STELLAR_CAPTIVE_CORE_HTTP_PORT`
   * (I am not sure about this due to being too magical) If `--remote-captive-core-url` is set (e.g. http://host:port/ ) we could default `--stellar-core-url` to `host:11626`.
* Match the log debug level of captive core to that of Horizon.

@tamirms @bartekn Thoughts?

As negative points:

1. I feel like my design may be too restrictive (e.g. it doesn't cover the testing options I mentioned above) which we may end up regretting. As an alternative we can allow appending text to the generated file or even supplying a full captive-core config file in full, but this beats the purpose of generating the file.
2. One of the goals is to abstract out Core's configuration, but I think we may end up leaking underlying details anyhow due to reasons like (1)

**Comment by bartekn** [comment]
> My initial design for this is

I think it looks good, we can always tweak config options before an RC. 

> One of the goals is to abstract out Core's configuration, but I think we may end up leaking underlying details anyhow due to reasons like (1)

I think one advantage we're missing is that by generating a file we remove the possibility of users making some big mistake in a configuration. We also prevent having to test Horizon with huge config matrix to ensure it works with all the options settable  in stellar-core.cfg that can affect the integration.

> it doesn't cover the testing options I mentioned above 

We can always add extra values we need later (ex. `MANUAL_CLOSE`).
