### ISSUE TITLE
State verifier test is flakey

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3371]
I wasted quite some time trying to debug a problem in https://github.com/stellar/go/pull/3368 because I thought the state verifier test was legitimately failing at https://app.circleci.com/pipelines/github/stellar/go/7096/workflows/b59bb5b9-004e-4b10-ac3e-7da3af6f43ad/jobs/34554

```
    protocol14_state_verifier_test.go:130: 
        	Error Trace:	protocol14_state_verifier_test.go:130
        	            				protocol14_state_verifier_test.go:110
        	Error:      	Should be false
        	Test:       	TestProtocol14StateVerifier
        	Messages:   	State is invalid!
 ```

However, the test didn't fail when re-running the tests.

**Comment by bartekn** [comment]
For future debugging, relevant error is here:
```
time="2021-01-22T19:01:10.051Z" level=info msg="Creating state reader..." ledger=15 pid=9441 service=ingest subservice=state_verify
time="2021-01-22T19:01:10.078Z" level=info msg="Batch added to StateVerifier" ledger=15 pid=9441 service=ingest subservice=state_verify total=6
time="2021-01-22T19:01:10.078Z" level=info msg="State verification finished" duration=0.026547204 pid=9441 service=ingest
time="2021-01-22T19:01:10.078Z" level=error msg="STATE IS INVALID!" err="verifier.GetLedgerKeys: Entries (6) not found locally, example: AAAADwAAAAAAAAAABfbg5jOaIVRsKcIxhw4eHbtM2uSE+ehGkXM3e8pBO8gAAAAAOmmdAAAAAA8AAAAAAAAABgAAAAAAAAAAAAAAAAEAAAAAAAADAAAAAAOxVv4WlCHmlJcKhj+50ig5sUyKgDcVwmuDzf6ifLo4AAAAAwAAAABoSKEf+W3s/k9yGFhCftvZSEbTQAEY7hWV5xotsJUhVAAAAAMAAAAAmrAozwr4fwoRRM8hzTn0Vzfu2NOTlLeEsqMms0DWxV8AAAADAAAAAQAAAAAAAAAAAAAAAAHJw4AAAAACAAAABgAAAAAAAAADAAAAAAAAAAEAAAAAc3b96I5M1hzA+ylKF4az8dBh9fLxyldGX6qTIhG5RtYAAAAAAAAAAAAAAAEAAAABAAAAAHN2/eiOTNYcwPspSheGs/HQYfXy8cpXRl+qkyIRuUbWAAAAAA==" pid=9441 service=ingest
```

**Comment by 2opremio** [comment]
It happened again https://app.circleci.com/pipelines/github/stellar/go/7111/workflows/91e13f9d-33f7-46f3-9998-ec3eb32c474d/jobs/34691

**Comment by 2opremio** [comment]
It happened a couple more times as part of the same PR

**Comment by 2opremio** [comment]
Another occurence: https://app.circleci.com/pipelines/github/stellar/go/7126/workflows/c153bc98-5abf-40ac-81b3-5c3c6dbeb283/jobs/34829

**Comment by bartekn** [comment]
OK, I figured out why it's happening. In accelerated mode ledgers are closed every second and checkpoints are created every 8 ledgers (~8 seconds). It means that state verifier is also run more often: every 8 seconds. Now, in `TestProtocol14StateVerifier` there's a check here to ensure rebuilding state works:
https://github.com/stellar/go/blob/974612507b87392459c110ebd492f507422ea062/services/horizon/internal/integration/protocol14_state_verifier_test.go#L106-L108

Because of the faster checkpoint rate, the following chain of events is possible:
1. State verification completes.
2. We trigger state rebuild (the snippet above).
3. New state verification routine starts, while state is still being rebuilt.
4. This triggers invalid state error and test fails.

I was thinking about it for a while and I have a few solutions (unfortunately none is perfect):
1. Trivial: just remove state rebuild case. Unfortunately, if we move it to a separate test, it's still possible that this issue will occur from time to time.
2. Create a new Horizon flag that will make state verify run every X checkpoints instead of every checkpoint. Then we can set it to some value higher than one (2-3?) so we will have enough time to rebuild state between verifier runs.
3. We can create a special http endpoint (available via admin port) that will stop state verifier runs or allow triggering them manually.

As of now, I think I can do 1 very quickly to fix the test and then work on 2. I think 2 is a better solution because it actually may be useful for some users who don't want to run verifier that often. Thoughts?

**Comment by ire-and-curses** [comment]
I like that plan. Add it to team meeting for quick discussion?
