### ISSUE TITLE
Allow setting BUCKET_DIR_PATH when starting Stellar-Core in captive mode

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3437]
### What problem does your feature solve?

Some users would like to specify where Stellar-Core stores bucket files because a default `/tmp` location is not always right (small partition, etc.)

### What would you like to see?

A new config flag that is forwarded to Captive Stellar-Core config (both online and offline modes).

### What alternatives are there?

Ideally, Stellar-Core team implements https://github.com/stellar/stellar-core/issues/2942 so there is no need to store bucket files on disk.

**Comment by Shaptic** [comment]
According to [the Golang documentation](https://golang.org/pkg/os/#TempDir), we should be able to customize this with no changes to the codebase:

> On Unix systems, it returns `$TMPDIR` if non-empty, else /tmp. On Windows, it uses `GetTempPath`, returning the first non-empty value from `%TMP%`, `%TEMP%`, `%USERPROFILE%`, or the Windows directory. On Plan 9, it returns `/tmp`.

That means a user can customize where their Core `buckets` go via `TMPDIR=~/.cache horizon --db-url=...`. If we can document this scenario, I think that will close this issue. Thoughts @bartekn?

**Comment by bartekn** [comment]
I think we should have a separate flag, even given it's configurable via `TMPDIR`:
* We need users to set this value explicitly, we had at least two users who run of space because their `/tmp` partition was too small. So not setting `TMPDIR` will default to `/tmp` and this will cause the similar issues again.
* `TMPDIR` is not descriptive enough.
* It can affect other apps if set globally instead of per process.
* If https://github.com/stellar/stellar-core/issues/2960 is implemented this folder will not be _temporary_ anymore. It will be better to persist files between captive core runs because bucket files will be reused.

**Comment by Shaptic** [comment]
Based on our conversation with ops, here's the strategy moving forward:

- We'll introduce a parameter (ideas: `--storage-directory`, `--bucket-directory`, `--captive-core-bucket-directory`; patents are pending) that will be passed along to Core's `BUCKET_DIR_PATH`.
- This will be the **current directory** by default, in order to make it obvious that there are large chunks of data being generated and encourage users to set the parameter accordingly when they notice this.
- Ops will set this to `/var/lib/stellar` in their packaging-based deployments.
- `/tmp` and friends will no longer be used.
