### ISSUE TITLE
Feature Request: Get Transactions for Account where Account is the Source

### ISSUE THREAD

**Issue by mootz12** [stellar/go#3688]
### Feature Request

Ability to query for Transactions where a given account is the _Source Account_ of the transaction using Horizon.

### What problem does your feature solve?

Currently, there is no Horizon way to query for Transactions by the _source account_. The `accounts/:account_id/transactions` endpoint functions by loading all transactions where the given account has participated in the transaction.

This means that to determine Transactions where an account is a source account, you have to wade through all transactions an account has participated in. This can be especially problematic with the current reality of "ad accounts" spamming 1 Stroop payments to an account. If this account is somewhat centrally related to an application or protocol, it also becomes a target of a 1 Stroop payment spam attack that could cause performance/stability issues for the app.

### What would you like to see?

A new parameter on the `accounts/:account_id/transactions` to allow for only fetching transactions where the account is the source.

```
accounts/:account_id/transactions?[current query params]&is_source{true,false}

is_source would be optional and default to false
```

I don't really know Go - but a code change suggestion could be for `/services/horizon/internal/db2/history/transaction.go#L67`:
```
// ForAccount filters the transactions collection to a specific account
func (q *TransactionsQ) ForAccount(ctx context.Context, aid string, bool isSource) *TransactionsQ  {	
    var account Account
    q.Err = q.parent.AccountByAddress(ctx, &amp;account, aid)
    if q.Err != nil { 
        return q
    }
    
    if isSource {
        q.sql = selectTransaction.Where("ht.account = ?", account.ID)
    }
    else {
        q.sql = q.sql.
            Join("history_transaction_participants htp ON htp.history_transaction_id = ht.id").
            Where("htp.history_account_id = ?", account.ID)
   }
        
    return q
}
```
I want to note that I am not sure how performant this query might be. It might require some indexing of the `account` field of the `history_transactions` table to truly be efficient.

### What alternatives are there?

If the above query is not performant, an option to add an `is_source` column to the `history_transaction_participants` table could be explored to allow the query to still function in mostly the same manner as it does today. The disadvantage here would be to add more data to an already large table.

**Comment by leighmcculloch** [comment]
Will this filter by transaction source account only, or operation source account too, and what about fee account? Is the goal to find transactions that only consume sequence numbers of the account (transaction source account), or transactions where the account chose to do something (transaction source account, operation source account, fee account).

I suspect for most applications it is more useful to query transactions that the account conceptually sourced by being a source on an operation or a few account too, and not just transactions where an accounts sequence number was consumed. Or possibly we need more fine grain filtering on all these things and combinations of these things. 

cc @tyvdh

_I asked the same question on the PR https://github.com/stellar/go/pull/4035/files#r743691733, but probably with discussing in the context of the original feature request._

**Comment by tyvdh** [comment]
From my perspective this is a useful feature add on it's own. Op and Fee filtering would also be useful. Where these are used in the Stellar Turret smart contract design you can directly control the transaction composition contract and utilize the transaction source filtering feature. Many times it's not the transaction source itself that matters but the ability to safely track interactions. For example we use the trades endpoint via custom proxy assets to achieve this goal now. It's very messy, convoluted and adds a lot of ops to otherwise clean transactions but it works. With transaction filtering this will get cleaner, if/when we add op, fee, effect, etc. filtering this will continue to improve the contract designs we can get away with safely.

There are many ways to achieve desired outcomes, it's just most often right now they result in _very_ complex XDR flows and otherwise unnecessary minimum balance increases in order to avoid and mitigate against possible attack or lockup vectors.

---

If anyone is interested in looking more deeply into how smart contracts are currently designed I'm more than happy to walk you through my `SmartNFTs` which are Stellar Turret smart contracts running on the public network.

https://nft.kalepail.com/smart-nft-00
https://nft.kalepail.com/smart-nft-01

There are drop docs and links to the actual contract code but due to the current Horizon limitations they may be a bit tricky to decipher what or why certain operational sequencing decisions were made. So I'm happy to walk anyone through these to help better explain the issues with the goal of creating better solutions.

**Comment by tyvdh** [comment]
Also cc: @mootz12 as they're the ones currently building the really complex financial products on top of Stellar Turrets and are most strongly feeling this issue today.

**Comment by mootz12** [comment]
> Is the goal to find transactions that only consume sequence numbers of the account (transaction source account), or transactions where the account chose to do something (transaction source account, operation source account, fee account).

The goal would be to find `transactions where the account chose to do something`. To provide a little bit more context, most of our smart contracts will result in an XDR such that:

- The end user is the Transaction Source (one getting the seq bump)
- Some operation occurs where a turret controlled account is the source. For example, this could be a payment from one turret controlled account to another. We want to be able to find this operation, without the risk of bad actors forcing us to wade through thousands of operations / transactions. 

---

We don't have an immediate use case for `transactions that only consume sequence numbers of the account`. Thus, I don't see a ton of value in more advanced filters at this point. I'd be happy with a list of transactions or operations an account had to sign for, regardless if it was account fees, transaction source, or operation source.

Let me know if you need more details, or a more specific example.

**Comment by leighmcculloch** [comment]
Reopening because I don't think #4035 completely addresses the feature request, at least according to https://github.com/stellar/go/pull/4035#discussion_r743719035. As @mootz12 indicated above, and I'm copying the relevant piece below, the request wasn't to filter transactions by whose sequence number is consumed, but by who conceptually sourced or caused an affect on the account.

>a list of transactions or operations an account had to sign for, regardless if it was account fees, transaction source, or operation source.

The goal is to separate transactions that the account had a hand in causing from transactions it didn't.

**Comment by ire-and-curses** [comment]
@mootz12 it sounds like you're saying the feature as currently implemented would not be sufficient (see Leigh's [comment](https://github.com/stellar/go/issues/3688#issuecomment-962056842) ). Is that correct?

We could get this as currently implemented (filter by transaction source account only) into the next Horizon release. If that isn't sufficient, we'll need more time to evaluate whether we can cover operation source accounts as well (this could be much harder).

**Comment by leighmcculloch** [comment]
To be clear, what is currently implemented in #4035 is: `transactions that only consume sequence numbers of the account`.

**Comment by 2opremio** [comment]
> Reopening because I don't think #4035 completely addresses the feature request

It does address what's described in the issue. If that's not what the OP wants anymore, then I would much rather have this issue closed and create another one with better requirements to avoid mixing things up further.

> To be clear, what is currently implemented in #4035 is: transactions that only consume sequence numbers of the account.

I think that's a convoluted definition. What #4035 implements is transactions whose Source field in XDR matches the account provided.

> The goal would be to find transactions where the account chose to do something

This definition is really lax (even with the examples below it) and very different from the issue's description, which is explicit about filtering by the transaction's source account. 

> We don't have an immediate use case for transactions that only consume sequence numbers of the account

Again, I am confused, since this seems to contradict the description in current issue.

Anyways, @mootz12 please open a new issue to precisely define your requirements. Editing this issue will just lead to further confusion.

I will also revert #4035 since no one seems to have any use for it.

**Comment by mootz12** [comment]
To answer `ire-and-curses` question here:

Correct. The way the ticket / solution is currently written doesn't provide much immediate use for Stellar Turrets and our use case. It looks like my initial analysis was wrong.

---

cc: @2opremio - I'll open a new issue with a clearer requirement. Apologies for the trouble. I think I was mistaken for what the `account` field on the `history_transaction` represented back when I created this issue.

**Comment by leighmcculloch** [comment]
@mootz12 Thanks for helping us better understand the use case so we can solve it more completely! Stellar transactions are very flexible and an account can conceptually source or cause a transaction, operation, or an effect on an account, without being the literal transaction source account so it is understandable that this isn't clear. I'll keep an eye out for the new issue.

**Comment by mootz12** [comment]
I recreated the issue with hopefully more clarity as to our requirement.

Please see -> https://github.com/stellar/go/issues/4051
