### ISSUE TITLE
Consider adding a flag in Horizon to reset captive core DB

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/go#4067]
It would be useful to have a flag in Horizon that runs `new-db` on captive core. This is needed in case there is a bug in stellar-core that corrupts the database, so that an operator can easily rebuild the minimal state and join the network. To do this, Horizon would need to run the following core command: `stellar-core new-db --minimal-for-in-memory-mode`

**Comment by sreuland** [comment]
possibly related to #4454 design aspects for reusing on-disk captive core storage path scenario.

**Comment by sreuland** [comment]
@marta-lokhova @jcx120 , I think the intent requested here for on-disk reuse feature to save time rebuilding has been implemented as of https://github.com/stellar/go/pull/4471, the approach taken was to automate when the captive-core on-disk db can be reused or reset rather than a user set flag, so, I think this issue can be moved to done/closed?

**Comment by marta-lokhova** [comment]
Closing as done
