### ISSUE TITLE
clients: cant force disable http2 (or support custom http transport)

### ISSUE THREAD

**Issue by JokerCatz** [stellar/go#4154]
you can do some change like this

https://github.com/grafana/k6/pull/2222/files

the golang old version has http2 deadlock bug , if use goroutine and node rpc or service provider make his gateway to support http2 , the http connection pool possible all stop and never return , even you set all possible timeout configs

**Comment by leighmcculloch** [comment]
Thanks for opening this issue. Could you clarify which client or which service the issue is occurring on?

**Comment by JokerCatz** [comment]
pure golang

https://github.com/golang/go/issues/32388

**Comment by leighmcculloch** [comment]
>I use clients folder

Which client in the `clients/` folder are you using?

- `clients/federation`
- `clients/horizonclient`
- `clients/stellarcore`
- `clients/stellartoml`

Is it the `horizonclient`? I will assume so for the rest of this message.

>or support custom http transport

The `horizonclient.Client` object has a field `HTTP` that you can set with your own `http.Client` that has its own `http.Transport`.
https://pkg.go.dev/github.com/stellar/go@v0.0.0-20220103175749-70c952b3d8c9/clients/horizonclient#Client

> golang/go#32388

This issues appear to have been backported and fixed in Go 1.16.10 (https://github.com/golang/go/issues/48649) and Go 1.17.3 (https://github.com/golang/go/issues/48650). If you can maybe you can upgrade to those versions so that the bug does not affect you.

**Comment by JokerCatz** [comment]
okay , I checked , many thanx : )
