### ISSUE TITLE
txnbuild: Support muxed addresses (SEP-23) by default.

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#4164]
As part of the rollout of muxed accounts (addresses in the `M...` form which combine a `G...` address alongside a uint64 identifier), we need to make M-addresses supported by default. In #3527 we enabled their support via explicit _opt-in_; now, **developers should _disable_ supporting them only via explicit _opt-out_**.

This is (intentionally) a breaking change.

As a reminder, the following fields can contain a muxed account. Note that while the below list should be accurate, the XDR is always an authoritative source:

 - the `SourceAccount` of _any_ `Operation`
 - the `Destination` of the three payment operations: `PaymentOp`, `PathPaymentStrictReceive`, and `PathPaymentStrictSend`
 - the `Destination` of an `AccountMergeOp`
 - the `From` of a `ClawbackOp`
 - the `SourceAccount` of _any_ `Transaction`
 - the `FeeSource` of a `FeeBumpTransaction`

#3527 also includes cross-references to all of the subsequent SDK implementations.

Related PR: #4053, which might make handling M-addresses cleaner in some parts of the code now.

**Comment by 2opremio** [comment]
Here's what I plan to do (implementing it takes a while so I would rather get the design approved first).

1. Rename the `withMuxedAccounts` to `withoutMuxedAccounts` in the `txnbuild.Operation` interface. That is:
```
type Operation interface {
	BuildXDR(withMuxedAccounts bool) (xdr.Operation, error)
	FromXDR(xdrOp xdr.Operation, withMuxedAccounts bool) error
	Validate(withMuxedAccounts bool) error
	GetSourceAccount() string
}
```
  to 

```
type Operation interface {
	BuildXDR(withoutMuxedAccounts bool) (xdr.Operation, error)
	FromXDR(xdrOp xdr.Operation, withoutMuxedAccounts bool) error
	Validate(withoutAccounts bool) error
	GetSourceAccount() string
}
```

It's not great since the API will only change semantically, giving the opposite interpretation to an existing parameter, but I cannot think of a better way.


2. Change the parameters of `NewTransaction()`, `TransactionFromXDR()` and `NewFeeBumpTransaction()` , that is:

  * Renaming `TransactionParams.EnableMuxedAccounts` to `TransactionParams.DisableMuxedAccounts`
  * Renaming `TransactionFromXDROptionEnableMuxedAccounts` to `TransactionFromXDROptionDisableMuxedAccounts`
  * Renaming `FeeBumpTransactionParams.EnableMuxedAccounts` to `FeeBumpTransactionParams.DisableMuxedAccounts`


@leighmcculloch @bartekn @tamirms @Shaptic . Let me know if you are OK with these changes. If I don't get an answer by Monday EOD I will implement them as described above.

**Comment by leighmcculloch** [comment]
> It's not great since the API will only change semantically, giving the opposite interpretation to an existing parameter, but I cannot think of a better way.

I agree, inverting a boolean is relying 100% on us humans updating every location and dependency appropriately, and lets face it, our race doesn't have the best track record at inverting booleans (e.g. double negatives). 

@Shaptic Why do we need to support opt-out? We're entering a moment where muxed addresses are just part of reality, where we expect applications to handle them. In the rarest of cases where applications need that underlying G address they can simply extract it from the M address provided by the SDK.

**Comment by leighmcculloch** [comment]
@2opremio How about change `withMuxedAccounts bool` to a typed integer with some constants for on and off?

**Comment by Shaptic** [comment]
I agree, Leigh. I'm not sure where the idea of opt-out came from, but I thought the timeline was flag opts in -> flag opts out -> flag goes away. It seems like the middle step causes more problems and doesn't really provide any value, so I would agree that we should just drop the `withMuxedAccounts` (and its corresponding conditionals) entirely and always parse out full muxed addresses.
