### ISSUE TITLE
Update Horizon Docker image to support P19

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4377]
Update Captive Core in Horizon [Docker](https://hub.docker.com/r/stellar/stellar-horizon/tags) image to support P19 version.

**Comment by 2opremio** [comment]
To solve the `docker build` caching problems we have I think we should just add a build parameter with core's version. This will make docker cache things correctly.

Also, the horizon docker image tag should probably reflect the core version included (otherwise we may end up releasing mutable tags, with different core versions).

**Comment by leighmcculloch** [comment]
@2opremio There is conversation about this here: https://github.com/stellar/go/pull/4379#issuecomment-1123976580

**Comment by 2opremio** [comment]
@leighmcculloch thanks, I reposted it there.

**Comment by jcx120** [comment]
Closing this issue as its being addressed in https://github.com/stellar/go/pull/4379

**Comment by bartekn** [comment]
GH didn't autoclose?
