### ISSUE TITLE
horizon: `history_claimable_balances` is not cleared out by the reaper.

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#4396]
We should:

1. Make sure the reaper takes care of `history_claimable_balances`
2. Make sure all the other history tables are included.
3. Add a test that ensure all the `history_` tables in the DB are cleared out (in order prevent this problem from happening to tables added in the future).

**Comment by 2opremio** [comment]
maybe @sydneynotthecity may have a better querying suggestion?

**Comment by sydneynotthecity** [comment]
Do you know how expensive of a query cost is too expensive? 

Another option is that we could [create a trigger](https://stackoverflow.com/questions/13785855/how-to-log-data-change-in-postgresql) that tracked any record deletions in the `history_*` tables and logged them to an events logging table. We could set it up in a way where the deleted id was logged to the events table. Then, we could delete the orphaned entries based on a join to this events table, which should be significantly cheaper than joining on the original tables. 

Once the records were cleared out, we could either update an indicator in the event tables for `is_deleted = TRUE` or just wipe the records from the events table so that the table only retains orphaned records to be deleted.

**Comment by sydneynotthecity** [comment]
@2opremio the other point is the `history_transaction_claimable_balances` and `history_operation_claimable_balances` were missing indices for `claimable_balance_id` which is what was causing joins/searches on `claimable_balance_id` to be super slow. @sreuland added the indices as a test in #4455 and it looks like it has greatly improved query performance. 

It appears that the equivalent `liquidity_pools` tables are also missing indices on `liquidity_pool_id` only. My guess is that if we added those as well, we should see enough query performance improvement to be able to identify orphaned records by query, like you originally proposed.

**Comment by 2opremio** [comment]
let's wait for the indices to be added and retake this after that.

**Comment by bartekn** [comment]
https://github.com/stellar/go/pull/4518 clears orphans from `history_claimable_balances` and `history_liquidity_pools`. The last two remaining tables (`history_accounts` and `history_assets`) require indexes in other tables like `horizon_operation_participants`. @ire-and-curses agreed that new indexes should be add in one of the future releases after further tests.
