### ISSUE TITLE
exp/services/ledgerexporter: Extend tool to work on ledger ranges in parallel.

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#4426]
We need to extend the `ledgerexporter` tool to export ledgers in parallel (e.g. doable on AWS Batch-able), because single-process exporting is absolutely time-prohibitive for large (and dense) ledger ranges.

**Comment by 2opremio** [comment]
I started implementing a single-process parallel version using goroutines, but .... considering the current memory requirements of Captive Core I am thinking that's probably a bad idea.

Then, I thought about simply adding a new `--end-ledger` flag, which we could use to split out subranges across different processes, but that poses another challenge: There is race condition on the `/latest` path. I don't think we can get around using some sort of distributed lock.

Additionally, I am thinking whether it's OK to update the `/latest` path before all the prior ledgers are successfully exported (e.g. update `/latest` when ledger 35 is exported but ledger 34 hasn't finished yet). Depending on the answer to that we may want to choose different parallelization strategies.

**Comment by 2opremio** [comment]
@bartekn any thoughts about this? Using a distributed lock is going to be a bit of a pain in the ass. If we need to do so I think I would rather use Kubernetes instead of AWS Batch (were we can use things like https://github.com/werf/lockgate )

**Comment by 2opremio** [comment]
Actually, we could use a lock in the archive backend itself. For S3 we have [https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html](object locks)

**Comment by 2opremio** [comment]
Yes, it doesn't make sense to parallelize exporting online ledgers. However, how do you suggest we handle the update of the `/latest` path?

1. The network is at ledger 50000
2. The ledger archive is at, say ledger 10000, (as pointed out by the `/latest` path)
3. We want to use e.g. 4 workers (10k ledgers each), each in its own process
   * worker A: range 10001 to 11000
   * worker B: range 11001 to 12000
   * ....

How does `/latest` get updated? If we (wrongly) decided that each process updates `/latest` on its own, we have a race condition (e.g. if A finishes the processing last, `/latest` will end up with value 11000, which is incorrect).


Maybe we could cut corners and keep it simple e.g:

* we disable updating the `/latest` endpoint through a flag (which we supply to the exporter workers when running in parallel)
* we allow allow having gaps in the archive (so that we don't have to worry about only updating `latest` when all the prior ledgers have been exported)

thoughts?

**Comment by Shaptic** [comment]
This might require a bit of work, but we could have a `/latest.lock` and read+update the `/latest` file "atomically"...

**Comment by Shaptic** [comment]
> Additionally, I am thinking whether it's OK to update the /latest path before all the prior ledgers are successfully exported (e.g. update /latest when ledger 35 is exported but ledger 34 hasn't finished yet). Depending on the answer to that we may want to choose different parallelization strategies.

Currently, the indexer assumes that `/latest` is accurate. Specifically, it polls the file and if it grows, the assumption is that those ledgers are available to be exported. If we want that behavior to work (it was unclear at the time if we'd do real-time or batched index updates), then `/latest` needs to in fact be the latest.

**Comment by Shaptic** [comment]
Another suggestion: we can use a two-step model for parallelization: each process exports ledgers to its own (sub-)directory with its own `/latest` file, then another process merges them all into a single directory.

**Comment by Shaptic** [comment]
Done in #4443
