### ISSUE TITLE
horizon: ingest Account Credited / Debited effects for smart contract asset transfers

### ISSUE THREAD

**Issue by tamirms** [stellar/go#4725]
The upcoming soroban release will implement single asset balance assets. This issue is a subtask of https://github.com/stellar/go/issues/4722 .

We will need to emit "Account Credited" / "Account Debited" effects whenever a Stellar asset is transferred or clawed back from a Stellar account via a smart contract invocation. This will require modifications to the [effects ingestion processor](https://github.com/stellar/go/blob/soroban-xdr-next/services/horizon/internal/ingest/processors/effects_processor.go#L226). The changes should be pretty straight forward because we can iterate through the tx meta produced by the invoke host function operation and see if there are any ledger entry changes for trustlines.

prerequisite: #4747

**Comment by Shaptic** [comment]
Some remarks:

 * Is it possible to infer that a contract data ledger entry belongs to a SAC from the entry itself? e.g. how it's possible to detect whether a particular Ethereum contract represents (or at least mimics) an ERC-20 token? Or do you run into an issue of "it looks like a SAC and acts like a SAC but it isn't one"?
 * If we decide to store entries, could/should we do it in a way that's distinct from the rest of our database, e.g. storing it in sqlite? This would let us heavily imply that we are storing this data simply for the purposes of persistence, rather than trying to make it a "full-fledged" part of Horizon (e.g. part of the overall DB schema, plumbed to endpoints, complex queries, scalability, etc.).
 * Should Horizon talk to Soroban RPC for this data? :sweat_smile:

**Comment by Shaptic** [comment]
Thoughtful answers, thanks! I agree with you on all counts, just needed some rationale. 

Horizon/RPC ingestion sync can be mitigated by sharing a Captive Core, but I think you're right that the dependency might get hairy. My intent was to try to keep the SC and Classic worlds as decoupled as possible, but that doesn't seem possible :confused: 

On the first point, is there a way to generate meta that **must** be unique to the SAC? For example, one could have a method that returns a signature signed by the issuing account. Such a blob couldn't be returned by a non-SAC SC, since it'd need the issuer's secret. Though I guess in that case, the issuer itself could mimic the SAC and that method, but can an issuer deploy its own token twice (once via SAC and once via custom)?? 

Anyway, that's just a thought - maybe there's a clever construction there that Core can pull off and we can leverage to glean information.

**Comment by tomerweller** [comment]
I think we should embrace the events approach. and I agree there's no escape from saving some minimal contract data information. 

This is not special to Horizon. Any soroban downstream systems that ingests events will need to "know" about the capabilities of the emitting contract before being able to process it's events.
