### ISSUE TITLE
horizon: TestFillGaps and TestReingestDB are flaky

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#5035]
The TestFillGaps and TestReingestDB integration tests are flaky

Here is a failing instance: https://github.com/stellar/go/actions/runs/6039252190/job/16387478256

**Comment by 2opremio** [comment]
Another instance: https://github.com/stellar/go/actions/runs/6054511730/job/16432024057?pr=5034

**Comment by 2opremio** [comment]
This has been happening for a while (for a few stellar core builds I would say)

**Comment by graydon** [comment]
Hmm. The LedgerCloseMetaFrame sets its version to 2 when built on a >= v20 protocol ledger. But ... that actually happens _before_ upgrades are applied (in `LedgerManagerImpl::closeLedger` , which means that when we are passing through the upgrade ledger we build a LedgerCloseMetaFrame thinking we're closing a v19 header (which will set version to 1), but the header we actually have when we complete the close is a v20 header.

Probably started failing with Garand's change to enable eviction (which is asserting this condition) but it was wrong for months before. The test `meta stream contains reasonable meta` should probably have caught this, but it's possible the checking isn't strict enough to catch the _exact_ transition ledger (i.e. it might admit the case that's occurring here where ledger X that transitions from v19->v20 is emitting a v19 LCM, and only X+1 emits a v20 LCM). Tightening this test should accompany any fix.

Relatively straightforward fix -- just carefully adjust the LCMF construction path in `closeLedger` to happen after upgrades and make sure doing _that_ doesn't break anything else -- just another symptom of code we haven't got especially strong testing of yet.

**Comment by graydon** [comment]
From conversation, a summary:

- For a ledger that upgrades from protocol vN to vN+1, we currently have two different assumptions in different parts of the ledger-close path:
  - In `closeLedger` we mostly treat the ledger as being on vN, eg. during tx apply and LCM construction
  - In the final stage, when we call `ledgerClosed`, we pass vN+1 because the upgrade completed and modified the ltx header, and we fish the protocol out of the ltx header
- This is _probably_ a historical mistake but it's far too late to change: we pass vN+1 to the bucketlist, for example, which bakes it into the bucket meta record for the newly formed bucket (and activates any vN+1-gated code). 
- The LCM we construct in `closeLedger` has lately (with the eviction code) started to be _amended_ in `ledgerClosed` and this is the source of the bug: it was constructed thinking it was a vN LCM, but it gets further amended under the assumption that it's a vN+1 LCM.
- There are a couple ways we can fix this:
  1. Since the LCM amending only happens on-or-after v20, and there will be nothing much to do on the v19->v20 boundary ledger, we can just relax the assertion that's tripping here and let the LCM-amending methods work in v19 as well. Make them no-ops -- you can call them but they just won't access the v20-related fields of the LCM. Put a big comment in explaining why this is ok and hope there's no other weird case that we're letting through by weakening that condition.
  2. Add a method to the LCM that fishes out the protocol version _it was constructed with_ and use that as the condition in `ledgerClosed` (and its callees) to decide to call the LCM-amending methods, rather than the post-close ledger protocol number. Again, if we do this there had better be a big comment explaining it, and some tests checking, because it's very subtle!
