### ISSUE TITLE
services/horizon: emit new metrics counters for timeouts

### ISSUE THREAD

**Issue by sreuland** [stellar/go#5217]
### What problem does your feature solve?
no metrics keys capture when horizon app server triggers a db session disconnect/abort due to CONNECTION_TIMEOUT or http client disconnects which trigger a similar db session disconnect/abort.

### What would you like to see?
new counter metrics key:
`horizon-db-session-forced-disconnects_total`
with two labels:
`server` - counter of occurrences of db session disconnects that were triggered due to CONNECTION_TIMEOUT
`client` - counter of occurrences of db session disconnects that were triggered due to early closure of client http connection.

**Comment by jacekn** [comment]
We also have automatic closure of idle connections if certain settings are set. Maybe another label for this would be useful? Something like "cleaned_up_idle" or something similar?

**Comment by sreuland** [comment]
> We also have automatic closure of idle connections if certain settings are set. Maybe another label for this would be useful? Something like "cleaned_up_idle" or something similar?

@tamirms @mollykarcher , would this additional metric of idle connection closure be worthwhile to include? I'm thinking not as much due to nature of this session doesn't have any sql actively executing on db server at the time of session closure by client db pool, but would like to garner consensus. also, i'm not really sure how to detect these closures in an ongoing basis from horizon runtime, it will require some research to confirm if there is path to retrieving the stat from go db pool package.

**Comment by tamirms** [comment]
On the client side we can close idle connections by enforcing the `--horizon-db-max-idle-connections` flag. We are able to get some metrics on connections closed due to this limit through https://pkg.go.dev/database/sql#DBStats and these metrics should already be available on prometheus https://github.com/stellar/go/blob/master/support/db/metrics.go#L187-L227

We also configure  [idle_in_transaction_session_timeout](https://github.com/stellar/go/blob/master/support/db/main.go#L189) when establishing new connections in our pool.  I think the error code returned by postgres for sessions terminated by the idle_in_transaction_session_timeout config is 
`25P03 | idle_in_transaction_session_timeout` (see https://www.postgresql.org/docs/12/errcodes-appendix.html )

It would be nice if we could extract metrics on how queries / transactions  fail / timeout directly from postgres. But I looked through https://www.postgresql.org/docs/current/monitoring-stats.html and I couldn't find anything useful
