### ISSUE TITLE
Single source asset optimization for pathfinding algorithm

### ISSUE THREAD

**Issue by tylerthedeveloper** [stellar/go#558]
If I know the source asset I would like to use but have multiple asset balances, then the pathfinding algo becomes computationally more expensive trying to find all the paths for the different assets I have a trustline with.

Under the hood it would be great to allow a single asset to be chosen to speed up the time it takes to locate the path(s) desired strictly between a -> b and not for the undesired assets.

**Comment by tylerthedeveloper** [comment]
@bartekn why is this being closed in both locations after it was asked to be moved here?

This could yield major performance enhancements.

**Comment by bartekn** [comment]
The path finding algorithm is much faster after the changes in https://github.com/stellar/go/pull/719. If the single source idea was only to speed it up then I think we can close this.

**Comment by tomquisel** [comment]
It's unintuitive, but because of the way pathfinding works, I think this change will make the results higher quality, but slower. The algorithm does a breadth-first search starting from the destination asset, and finds the first 20 paths that end at source assets. Limiting to just one asset means it'll need to do a more exhaustive, deeper search to find 20 paths.

We should first do a further round of optimization (moving order books into memory, #849), and then come back and make this change. I support the change, as it's valuable to be able to get high quality results for a single source asset. This is a very common use case.

**Comment by patrickxb** [comment]
Specifying a source asset to ensure high quality payment paths would be very useful.

**Comment by tylerthedeveloper** [comment]
I'm no longer tracking this if you want to close it - it sounds like there was a ton of good debate here and Im curious where we left off
