### ISSUE TITLE
OpenAPI 3 specification for Horizon API

### ISSUE THREAD

**Issue by Unisay** [stellar/go#689]
At the moment Horizon API is documented on the website,
but the documentation is imprecise (and often doesn't match actual responses) - for example there is not enough information about required/optional fields etc. Its also not possible to generate API clients using such a documentation.
[OpenAPI](https://swagger.io/specification/) is a well known standard and its recent version allows to keep API definitions DRY. Please consider defining Horizon API using OAS 3.

**Comment by chatch** [comment]
I just looked at a couple of possible approaches to implementing this.

one approach is to embed openapi snippets in code comments.  [go-swagger](https://github.com/go-swagger/go-swagger) can generate a full spec from these snippets. I think this would be ideal however it [only supports the older 2.0 version of the spec](https://github.com/go-swagger/go-swagger/issues/1122) at this stage. looks like a fairly big chunk of work to update it too.

possibly another tool exists although i couldn't find anything out there that could do generation from code or comments ...  

or .. define a simple syntax to embed snippets and write a script to pull them out and aggregate them.

or .. simply write up the openapi spec file and put it in docs/ or similar (as the api markdown is now).  later on if tooling supports it and it's preferred snippets could be moved into code comments.

what do people think?

**Comment by MartinThoma** [comment]
I don't know why this hasn't received more attention ... or attention at all. I absolutely love the idea of having a REST documentation for Horizon!

I'm mainly a Python developer and just started reading about [stellar-model](https://github.com/StellarCN/stellar-model), a Python package which provides typed versions of the models. Such projects would profit a lot from having an OpenAPI spec.

I see 3 general ways of getting it:

1. **Auto-Generate Spec from Code**: My company uses Python and a coworker developed [drf-spectacular](https://github.com/tfranzel/drf-spectacular) so that we can have OpenAPI 3 specs for our services
2. **Auto-Generate Code from Specs**: Zalando developed [connexion](https://github.com/zalando/connexion) for Python
3. **Manually write but, make use of tests to check they match**: Given an OpenAPI 3 spec, one can automatically generate requests against a running server. If they fail, something might be wrong in the specs.

I strongly prefer (1). 

(2) has the issue that it's typically harder to write OpenAPI specs than to write code in the framework you're used to.

(3) has the issue that it's impossible to test endpoints that were forgotten in the spcs, you need a running server, you might not be able to test everything properly

However, as an intermediate solution even just manually writing + updating a `spec.yaml` would be very helpful.

**Comment by Shaptic** [comment]
We actually do have an OpenAPI schema :upside_down_face: https://github.com/stellar/stellar-docs/tree/main/openapi/horizon

**Comment by FrankSzendzielarz** [comment]
> We actually do have an OpenAPI schema 🙃 https://github.com/stellar/stellar-docs/tree/main/openapi/horizon

Haha. I just noticed that the previous questions and answers were from like 2018 and 2021 :-D I asked Stella AI and it also said there was no OAS spec. This is pretty funny. Why is this issue still open then?

**Comment by Shaptic** [comment]
Hah, @FrankSzendzielarz, probably because we forgot there was an issue for it
