### ISSUE TITLE
Horizon: it should keep connections open (?)

### ISSUE THREAD

**Issue by ramontayag** [stellar/go#705]
Horizon closes the connection after the `limit` is reached. Is this intended?

```js
const es = new EventSource('https://horizon.stellar.org/transactions?limit=200');
es.addEventListener('open', () => {
  console.log('opened')
});
es.addEventListener('message', e => {
 console.log(e)
});
es.addEventListener('error', (event) => {
  console.log(event);
});
```

The error event gets called every 200 transactions.

**Comment by lechengfan** [comment]
It's not ideal, but it's needed so that the SSE endpoint can respond with more data. According to the comment in services/horizon/internal/render/sse/main.go, 

> // Upon successful completion of a query (i.e. the client didn't disconnect
// and we didn't error) we send a "Goodbye" event.  This is a dummy event
// so that we can set a low retry value so that the client will immediately
// recoonnect and request more data.  This helps to give the feel of a infinite
// stream of data, even though we're actually responding in PAGE_SIZE chunks.

**Comment by ramontayag** [comment]
Why can't the connection stay open and the endpoint responds with more data when that data becomes available?

**Comment by bartekn** [comment]
If I remember correctly one of the reasons Horizon server disconnects client after sending `limit` events is because of rate limiting. This way, there's no special logic needed in both server (after closing a stream new HTTP connection is reestablished) and client (SSE reconnection is part of the protocol).

When it comes to the errors you are getting, this is part of the [protocol](https://www.w3.org/TR/eventsource/):
> When a user agent is to **reestablish the connection**, the user agent must run the following steps. These steps are run asynchronously, not as part of a task. (The tasks that it queues, of course, are run like normal tasks and not asynchronously.)
> 1. Queue a task to run the following steps:
>   1. If the readyState attribute is set to CLOSED, abort the task.
>   1. Set the readyState attribute to CONNECTING.
>   1. **Fire a simple event named error at the EventSource object.**

I also think this is strange but it's part of the protocol. One idea I have (not sure if it's correct) is to check `es.readyState` inside the error handler. Possible [values](https://developer.mozilla.org/en-US/docs/Web/API/EventSource/readyState) are:
* 0 — connecting (the error can be probably ignored, client is reconnecting)
* 1 — open (error while connection is open - probably a "real" error)
* 2 — closed (connection failed?)
