### ISSUE TITLE
Cannot use hook.Entries (type []logrus.Entry) as type []*logrus.Entry in return argument

### ISSUE THREAD

**Issue by mychell** [stellar/go#786]
Cannot use hook.Entries (type []logrus.Entry) as type []*logrus.Entry in return argument.

when using with go 1.11

**Comment by tomquisel** [comment]
I believe this issue comes from using `go get` rather than `dep ensure` to get dependencies. @mychell can you confirm that the build works when you use `dep ensure` as decribed in the [building guide](https://github.com/stellar/go/blob/master/services/horizon/internal/docs/reference/admin.md#building)?

**Comment by leevlad** [comment]
I ran into this issue when importing from HEAD. Looks like you guys use `github.com/sirupsen/logrus@68cec9f21fbf3ea8d8f98c044bc6ce05f17b267a`, which is 1.5 years old.

My project uses the latest release of `logrus`, which seems to be incompatible with the one used here. Specifically the problem is that `Hook.Entries` has changed its signature from a slice of pointers to a slice of values.

Here's the old definition:
https://github.com/sirupsen/logrus/blob/68cec9f21fbf3ea8d8f98c044bc6ce05f17b267a/hooks/test/test.go#L18

and here's the current: 
https://github.com/sirupsen/logrus/blob/cdb2f3857cfba7388d28dfe38316b0a39e694215/hooks/test/test.go#L18

**Comment by leevlad** [comment]
Suggested fix would be to upgrade the repo to a current version of Logrus. This problem has been called out a few times already. Please consider that many users of this library will not be willing to downgrade to a 1.5 year old version of logrus:

https://github.com/stellar/go/pull/772
https://github.com/stellar/go/issues/575
https://github.com/stellar/go/pull/781

**Comment by leevlad** [comment]
A workaround for those using Go 1.11 Modules is to explicitly get the version of `logrus` used in this package:
`go get github.com/sirupsen/logrus@68cec9f21fbf3ea8d8f98c044bc6ce05f17b267a`
