### ISSUE TITLE
Rearchitect clients/horizon package

### ISSUE THREAD

**Issue by bartekn** [stellar/go#844]
The current version of `clients/horizon` originated in 2 methods built in bridge-served that were moved here and new features were just added without thinking much. It was never really designed well.

One idea to solve this is to build Horizon API blueprint that can be later used to autogenerate client libraries' code. The problem is we are currently in the process of redesigning Horizon so we are not sure what form the final API will have. It seems that given the bad state of the package we should just update it to "work" before Horizon API changes are in production.

Several thoughts and idea:
- It looks like the Call Builder pattern we are using in Java and JS SDKs works pretty well. We should prepare a single endpoint builder and check what are pros and cons of this design in Go.
- Methods like `HomeDomainForAccount()` or `SequenceForAccount()` that are used by other packages of monorepo should be still there but use a new Call Builders internally.
- The great thing is that we can use response structs from `protocols/horizon` package.
- In my opinion SSE streaming code after changes in https://github.com/stellar/go/pull/554 and https://github.com/stellar/go/pull/663 is in a good state (it follows the SSE protocol well). We should probably leave it but just connect to new code.

**UPDATE**
After  investigating various options, we have decided on what pattern to follow: See discussion below.
To complete this redesign, will be adding some tasks here that we can use to track the progress

- [x] Create experimental horizon client 
- [x] Create new request structs
- [x] Implement new request pattern for accounts endpoint
- [x] Write tests for new implementation
- [x] Write documentation new implementation
- [x] Repeat for other endpoints

Will continue to update this list through the course of implementation

**Comment by poliha** [comment]
I think we should be able to redesign the clients/horizon package so that it supports more endpoints and in such a way that implementing new endpoints are easy. 

The Call builder pattern works well and it should be implemented here too. As there is no traditional inheritance in Go, we can achieve the same functionality by [embedding](https://golang.org/doc/effective_go.html#embedding) the `struct` and `interface`
For example

```golang
type CallBuilderInterface interface {
	Call() (Response, error)
}

type CallBuilder struct {
	URL string
}

type Operation struct {
  id string
  CallBuilder
  
}
```
Assuming that the CallBuilder implements the interface, then we can do 
```golang
op := operation.New('123abc') 
op.Call()

// this is just an example. Some features are excluded.
```

Payments, transactions and other endpoints can be extended in this way. 

I believe all the responses from Horizon has been captures in protocols/horizon, so we should not need to define new Response types. 

Also, we can add Streaming to the proposed CallBuilder so that duplicated code can be reduced.

We can start implementing this for just one endpoint, see how it goes before extending.

**Comment by ire-and-curses** [comment]
Thanks for investigating this! I left a [long comment](https://github.com/stellar/go/pull/878#pullrequestreview-203050755) on the PR.

I thought about this some more, and did some research. The builder pattern is very common in Java, because the constructor is so inflexible. It lets you decouple construction from the object itself, and allow all kinds of partial constructions without explicitly setting hundreds of constructors.

In Go, the pattern is less common, because you can usually do partial configuration by just setting struct fields, and because the pattern screws up Go's error handling ([see here](https://www.calhoun.io/using-functional-options-instead-of-method-chaining-in-go/) for a discussion).

I think there are three basic approaches to implementing this. I sketched out some toy examples to illustrate.

**Option 1:** Simple structs. Example: https://play.golang.org/p/PIxg7pZbrDN
**Option 2:** Builder pattern. Example: https://play.golang.org/p/JPM9_4ohlfI
**Option 3:** Functional parameters. Example: https://play.golang.org/p/6r9XHviV6Q1

Structs are simple, and minimal boilerplate. But you can't validate arguments until the `Build()` step. The usage looks nothing like the JS SDK.

Builder pattern. Matches the JS SDK. Quite a bit of boilerplate. Hard to deal with errors (see approach in the toy example for one less than ideal way). Type issues and clunky API. Various problems outlined in PR comment above.

Functional options. Unusual API, doesn't directly match the JS SDK. Very flexible, allows custom build steps to be provided. Handles errors well. Use of closures may be somewhat mind-bending. Here are three good references that explain the concept.

* [Functional options for friendly APIs](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)
* [Self-referential functions and the design of options](https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html) (by Rob Pike!)
* [Using functional options instead of method chaining in Go](https://www.calhoun.io/using-functional-options-instead-of-method-chaining-in-go/)

Interested in anybody's thoughts about all this (@bartekn, @poliha, @tomquisel). My personal feeling is that functional options may be the best match to Go's design and limitations but I'd like to hear counterarguments. If we wanted, I could do a quick spike like @poliha did in #878 to learn more.

**Comment by poliha** [comment]
>Unusual API, doesn't directly match the JS SDK.

This is my issue with the Functional parameter approach. It deviates most from our goal of making the SDK's have similar usage. 

Simple structs is similar to what we have now. We basically have one client struct that implements all the methods of the interface.  It can lead to fairly large interfaces.

I think the issue we are having with the builder pattern is that we are trying to make it work strictly like how it works in Java and JS. 

Given that Go is different from JS and Java, do we want to focus on 
- Having the exact usage pattern or something similar?   or 
- Having all the endpoints available in a manner that is compliant with Go?

**Comment by ire-and-curses** [comment]
P.S. As for the issue of difficulty inferring types from Horizon, I am in favour of making the return more explicit, so that type is at a top level and can just be checked by the SDK and then mapped to the correct struct. If we added this but also returned everything we already do, would that be backwards-compatible?

**Comment by poliha** [comment]
Yes that sounds correct. That's one solution that might work because the operations already have a type_indicator in the response from horizon. Also, for any changes we make, the current endpoints will still be supported for a while. It won't be immediately deprecated.

**Comment by bartekn** [comment]
@poliha @ire-and-curses thanks for your research!

I think that the most important requirements of this API is a clarity when it comes to usage. Ideally methods and parameters should be self-describing so users don't need to check the docs every time they write a code (or even worse: the package code itself) to use it. So I think that functional version (option 3 from @ire-and-curses message) is actually hard to use. When you want to use `BuildCar` you need to find all structs that implement an interface or functions with a type: `CarBuildStep`. This is very similar to how `build` package looks like and it's super confusing.

I also understand now that builder pattern is not a perfect design in Go when we need to _extend_ it's functionality with _subclasses_ (actually embedding the structs). It's basically @poliha's PR or Option 2 in @ire-and-curses comment. For example, say we want to add common params in embedded struct (`CallBuilder`), to be able to chain method calls we need them to return `*CallBuilder`, ex:
```go
func (cb *CallBuilder) Cursor(value string) *CallBuilder {
	return cb
}

func (cb *CallBuilder) Order(value Order) *CallBuilder {
	return cb
}

func (cb *CallBuilder) Limit(value int) *CallBuilder {
	return cb
}
```
Now, if we want to actually make a call, we can't because `*CallBuilder` doesn't have methods we added to, say, `OperationsCallBuilder`. Here's a short [snippet](https://play.golang.org/p/HvvTRuzXqEC) I made.

Having said that, I think I'm leaning towards very expressive request structs (like Option 1). Something like [this](https://play.golang.org/p/iRU2sIkla0h). The big advantage is that you know what parameters you can send by just looking at the struct. We also prevent code duplication as code responsible for unmarshaling a given type (ex. page of operations or page of transactions) is in a single place. Finally, all return objects are strict, we don't return interfaces (including `interface{}`). I don't think, not returning errors before _build_ step is a big disadvantage.

**Comment by poliha** [comment]
Hey guys, thanks for the feedback. From the comments so far, this is what I have

|  Features | "Expressive" structs  | Strict builder pattern  | Functional params  | Modified builder pattern  |
|---|---|---|---|---|
| Simple and easy API  |  Y | Y  | N| Y  |
| Uses language constructs  | Y  | N|N |N |
| Minimal code duplication  | Y  | N| ?  |N |
| Error handling before build step  |N |N | Y  |  Y |
| Strict return types  |  Y |N | N|N |
| Pattern is consistent with other SDKs  |N |  Y |N |N |
| Removes need to type check returned operations  |N |N |N |N |

**legend**

Y = Yes; N= No; ? = Unknown

Let me know if there is anything I have missed out or represented inaccurately

So far, @bartekn 's suggestion seems to have more points in favour. Any more input(for or against) is welcome.

**Comment by ire-and-curses** [comment]
I guess I disagree that the functional parameters approach is hard to use/discover. Even with structs, you still have to know _which_ structs you want, and how to compose them to do what you need. I think that in the case of the `build` package, a key issue is the general variadic args everywhere, so you can't tell what you're supposed to pass. We wouldn't have that issue here.

That being said, I am pretty happy with the expressive struct approach outlined by @bartek. It is easy to understand, a standard Go approach, and less work than alternatives. I also agree that the error handling limitations probably aren't an issue here. I think we should go with that and see how it plays out.

@tomquisel Any other thoughts before we make a decision here and plow forward?

**Comment by tomquisel** [comment]
Sounds good! I'm a fan of the expressive struct approach too. I like that it's idiomatic to Go, and it's a good application of KISS. Let's move forward with it. We can always switch to another approach if it proves unwieldy.

I investigated reducing duplication by adding onto Bartek's `struct` example. I noticed that request objects will have duplicated fields (like many requests will have the standard `order`, `cursor`, `limit` fields). [This](https://play.golang.org/p/Ycm8a1v3PUH) is what I came up with. I don't particularly like it. Is there a better approach, or should we just duplicate those params? Duplicating doesn't seem like a big deal, since we can still pull out the `struct` -> url param string logic.

**Comment by ire-and-curses** [comment]
I think we should (reluctantly) duplicate. It keeps the API simpler for the user, and prevents us leaking the underlying base struct out to the user.

One thing: the JS SDK differentiates mandatory args by passing them into the builder constructor. Here we can't indicate what is mandatory since it's all in the same struct. I don't think this is a big deal though, we can document that and also provide an informative error message when `call()` is invoked.

**Comment by poliha** [comment]
Okay since we have a consensus, we will go ahead with the expressive structs. Will update the originial issue with a task list.
