### ISSUE TITLE
Better docs for Go SDK

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#863]
The JS SDK has a single API reference, and a number of useful walkthroughs that guide a new developer through the process of starting out with the API, linking and explaining key concepts. The Go SDK needs something equivalent. We do have Go doc generated for each library, but it is minimal, and it's not clear which parts are needed to start out coding against Stellar in Go. Currently, to use the SDK requires a lot of hunting around in the monorepo, and a lot of reading the code.

This issue is to fix the developer experience by bringing the docs to parity with the JS SDK.

**Comment by poliha** [comment]
The documentation generated by Godoc has some examples on how to use the functions, e.g [here](https://godoc.org/github.com/stellar/go/clients/horizon#example-Client-StreamLedgers), however these are scarce. 

Also, does the amount of information presented (documentation for the whole monorepo) make it overwhelming for a new user? If the SDK is on its own, maybe it might be less challenging?

What might also help is if the style of the generated docs can be changed. Having all the reference at the top of the page makes navigating cumbersome. 

Having example code on the developer website as we have for JS [here](https://www.stellar.org/developers/horizon/reference/endpoints/payments-all.html) will also be useful.

So it seems that to bring the Go SDK docs to parity with JS, we need to 

- Write better examples and comments with our codes in order to leverage godoc.

- If possible, explore better styling for the documentation generated by godoc

- Probably export the SDK from the monorepo

- Add examples to the developer website

**Comment by ire-and-curses** [comment]
There are actually code examples in the [getting started guides](https://www.stellar.org/developers/guides/get-started/create-account.html)! I missed that you can click on the examples to change the language (subtle grey font hard to see).

Unfortunately, the Godoc pages are not under our control - it appears they are automatically generated from crawling our repo. If we wanted more control we could look into generating and hosting our own docs, but there is some merit to having them in a standard community-expected location. So I think we are probably stuck with the styling for now. We can make a better index page tying the godocs together though.

Combining the suggestions above and plan from #861, we should 
- [ ]  Create a central README pointing out the necessary sub-libraries and their uses.
- [ ]  Audit examples in getting started guide, improve as needed.
- [ ]  Add create account example to getting-started guide for real network (not just Friendbot).
- [ ]  Fill out godoc for all client-facing libraries:
    - [ ] [clients/horizon](https://godoc.org/github.com/stellar/go/clients/horizon) (main client funcs)
    - [ ] [build](https://godoc.org/github.com/stellar/go/build) (construct operations for submission)
    - [ ] [protocols/horizon](https://godoc.org/github.com/stellar/go/protocols/horizon) (data structures for responses)
    - [ ] [keypair](https://godoc.org/github.com/stellar/go/keypair) (create/manipulate keys)
    - [ ] [strkey](https://godoc.org/github.com/stellar/go/strkey) (stellar network addressing)
    - [ ] [xdr](https://godoc.org/github.com/stellar/go/xdr) (native format representation)
    - [ ] [hal](https://godoc.org/github.com/stellar/go/support/render/hal) (Horizon paging data structures)
- [ ]  Add [examples like this](https://godoc.org/github.com/stellar/go/clients/horizon#Client.StreamLedgers) to godocs as needed.

We can discuss moving the SDK from the monorepo in a meeting, but I think it will be a challenge, since the libraries above are shared by lots of code.

**Comment by ire-and-curses** [comment]
Working through getting started guides, some fixes in [stellar/docs#432](https://github.com/stellar/docs/pull/432)

**Comment by ire-and-curses** [comment]
Once we have our first version of the new `exp/client` and `exp/txnbuild` libraries, we should revisit this issue and identify the most critical docs to add.

**Comment by ire-and-curses** [comment]
txnbuild: GoDocs, examples, README: #1191
