### ISSUE TITLE
exp/clients/horizon: add timeout setting

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#953]
The new Go client needs support for `timeout` (see [comment in stellar-core#1811](https://github.com/stellar/stellar-core/issues/1811#issuecomment-434315930) for details).

**Comment by poliha** [comment]
Hey @ire-and-curses I think the `timeout` that is referred to in the issue above has to be implemented in the transaction builder, using `maxTime`. See in the [JS SDK](https://github.com/stellar/js-stellar-base/blob/1ffbb78eb02a358181fbcf4c0c22ee4102fe2ec9/src/transaction_builder.js#L128). This will deal with timeouts for including the transaction in the ledger

However, we can also a `timeout` set when trying to submit the transaction to Horizon. As seen in the [JS SDK](https://github.com/stellar/js-stellar-sdk/blob/7699f0aa2b3d6640359db9f05f1496f95baf43e3/src/server.js#L95). This deals with getting a response from horizon so that the user doesn't wait indefinitely.  This can be done by horizon client

**Comment by ire-and-curses** [comment]
@poliha Good point - I'll raise a separate issue to add this to the transaction builder.

**Comment by poliha** [comment]
closed in #1042
